import { Cable, Translation, Language, StandardStructure, MaterialCategory, MaterialItem } from './types';

export const MATERIAL_CATEGORIES: MaterialCategory[] = [
  { id: 'cat-power', name: 'Forza Motrice', icon: 'Zap' },
  { id: 'cat-lighting', name: 'Illuminazione', icon: 'Sun' },
  { id: 'cat-fire', name: 'Antincendio', icon: 'Flame' },
  { id: 'cat-data', name: 'Reti Dati / Lan', icon: 'Network' },
  { id: 'cat-trays', name: 'Passerelle', icon: 'Layers' },
  { id: 'cat-solar', name: 'Fotovoltaico', icon: 'SunMedium' },
  { id: 'cat-cctv', name: 'Videosorveglianza', icon: 'Camera' },
];

export const MATERIAL_DATABASE: MaterialItem[] = [];

export const CABLE_DATABASE: Cable[] = [];

export const STANDARD_STRUCTURES: StandardStructure[] = [];

export const TRANSLATIONS: Record<Language, Translation> = {
  'en': {
    title: 'CableFill Pro',
    nav: {
      dashboard: 'Dashboard',
      trays: 'Cable Trays',
      conduits: 'Conduits',
      cables: 'Cables Database',
      admin: 'ADMINISTRATION',
      users: 'User Management',
      newProject: 'New Project',
    },
    sidebar: {
      overview: 'OVERVIEW',
      cableTrays: 'CABLE TRAYS',
      conduits: 'CONDUITS',
      cables: 'CABLES',
      database: 'PROJECT DATABASE',
      vault: 'VAULT',
      documentation: 'DOCUMENTATION',
      projectManagement: 'PROJECT MANAGEMENT',
      appSubtitle: 'ENGINEERING SYSTEM',
      userTitle: 'PRIVATE PROPERTY',
    },
    header: {
      currentModule: 'Current Module',
      searchPlaceholder: 'SEARCH ANALYSIS PARAMETERS...',
      lightMode: 'Light',
      darkMode: 'Dark',
      export: 'EXPORT',
      exportPdf: 'EXPORT AS PDF (.pdf)',
      exportCsv: 'EXPORT AS EXCEL (.csv)',
      generatingPdf: 'GENERATING PDF...',
    },
    input: {
      parameters: 'INPUT PARAMETERS',
      structureName: 'STRUCTURE NAME',
      structureType: 'STRUCTURE TYPE',
      dimensions: 'DIMENSIONS (mm)',
      fillLimit: 'FILL LIMIT (%)',
      addCable: 'ADD CABLE',
      calculate: 'RUN CALCULATION',
      width: 'Width',
      height: 'Height',
      quantity: 'Qty',
      standardSize: 'STANDARD SIZE',
      customSize: 'CUSTOM / OTHER',
      diameter: 'DIAMETER',
      size: 'SIZE (mmq)',
      tagPlaceholder: 'TAG / CIRCUIT (EX: C1, LIGHT...)',
      editTag: 'EDIT TAG...',
      hasSeparator: 'USE SEPARATOR (SEPTO)',
      mixedSystemsWarning: 'POWER AND DATA CABLES REQUIRE A SEPARATOR IN TRAYS.',
      conduitMixedWarning: 'MIXING POWER AND DATA CABLES IS PROHIBITED IN CONDUITS.',
      separatorRequiredWarning: 'CANNOT DISABLE SEPARATOR: BOTH POWER AND SPECIAL SYSTEMS ARE PRESENT. REMOVE ONE SYSTEM TYPE FIRST.',
      clearAll: 'CLEAR ALL',
      cableAdded: 'Cable added',
      cableRemoved: 'Cable removed',
      allCablesRemoved: 'All cables removed',
      searchCables: 'SEARCH CABLES...',
      favorites: 'FAVORITES',
      notes: 'PROJECT NOTES',
      notesPlaceholder: 'Enter technical notes, calculation assumptions or project observations...',
    },
    results: {
      utilization: 'UTILIZATION',
      status: 'GLOBAL STATUS',
      pass: 'PASS',
      fail: 'FAIL',
      totalArea: 'TOTAL AREA',
      usedArea: 'USED AREA',
      numberOfTrays: 'REQUIRED STRUCTURES',
      autoScaled: 'AUTO-SCALED',
      deltaMax: 'DELTA MAX',
      allow: 'ALLOW',
    },
    preview: {
      structuralPreview: 'STRUCTURAL PREVIEW',
      crossSection: 'CROSS-SECTION',
      isometric: 'ISOMETRIC',
      cableSchedule: 'CABLE SCHEDULE / CORRESPONDENCE',
      noTag: 'NO TAG',
      noCables: 'No cables added to project yet.',
      noSavedProjects: 'No saved projects found.',
      structure: 'STRUCTURE',
      limit: 'LIMIT',
      utilization: 'UTILIZATION',
      reset: 'RESET PROJECT',
      newProject: 'NEW PROJECT',
      deleteProject: 'DELETE PROJECT',
      project: 'PROJECT',
      saveProject: 'SAVE PROJECT',
      savedProjects: 'SAVED PROJECTS',
      loadProject: 'LOAD PROJECT',
      lastSaved: 'LAST SAVED',
      mustBeLoggedIn: 'You must be logged in to save projects.',
      saveError: 'Error saving project',
      unexpectedError: 'Unexpected error saving project',
      pdfExportError: 'Error exporting PDF',
      zoomIn: 'Zoom In',
      zoomOut: 'Zoom Out',
      fitToScreen: 'Fit to Screen',
      dashboard: 'Dashboard',
      shortcuts: 'Shortcuts',
    },
    management: {
      addNew: 'ADD NEW MODEL',
      name: 'MODEL NAME',
      width: 'Width (mm)',
      height: 'Height (mm)',
      diameter: 'DIAMETER (mm)',
      weight: 'WEIGHT (kg/km)',
      type: 'TYPE',
      category: 'CATEGORY',
      power: 'POWER',
      specialSystems: 'SPECIAL SYSTEMS (DATA/SECURITY)',
      actions: 'ACTIONS',
      save: 'SAVE MODEL',
      cancel: 'CANCEL',
      delete: 'DELETE',
      edit: 'EDIT',
      existingModels: 'EXISTING MODELS IN DATABASE',
      existingCables: 'EXISTING CABLES IN DATABASE',
      saveSuccess: 'Model saved successfully!',
      deleteSuccess: 'Model deleted successfully!',
      confirmDelete: 'Are you sure you want to delete this model?',
    },
    auth: {
      login: 'LOGIN',
      register: 'REGISTER',
      username: 'USERNAME',
      password: 'PASSWORD',
      signIn: 'SIGN IN',
      signUp: 'REQUEST ACCESS',
      needAccount: 'Need an account? Request access',
      haveAccount: 'Already have an account? Sign in',
      adminPanel: 'ADMIN PANEL',
      logout: 'LOGOUT',
      pendingApproval: 'Your account is pending approval by an administrator.',
      connectionError: 'Error connecting to the server.',
      email: 'EMAIL',
      name: 'NAME',
      systemName: 'Rilo Elettrico',
      passwordRequired: 'Password is required.',
    },
    userManagement: {
      title: 'USER MANAGEMENT',
      users: 'USERS',
      approve: 'APPROVE',
      delete: 'DELETE',
      status: 'STATUS',
      approved: 'APPROVED',
      pending: 'PENDING',
      role: 'ROLE',
      confirmDelete: 'Are you sure you want to delete this user?',
      createError: 'Error creating user',
      fetchError: 'Error fetching users',
      approveError: 'Error approving user',
      updateError: 'Error updating user',
      deleteError: 'Error deleting user',
      unknownError: 'Unknown error',
      userCreated: 'User created successfully!',
      userApproved: 'User approved successfully!',
      userDeleted: 'User deleted successfully!',
      changesSaved: 'Changes saved successfully!',
      newUser: 'New User',
      searchPlaceholder: 'Search by name or email...',
      allRoles: 'All Roles',
      createNewUser: 'Create New User',
      nameLabel: 'Name',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      passwordRequired: 'Password is required.',
      accessLevel: 'Access Level',
      accessibleModules: 'Accessible Modules',
      cancel: 'Cancel',
      creating: 'Creating...',
      createUser: 'Create User',
      nameHeader: 'NAME',
      emailHeader: 'EMAIL',
      levelHeader: 'LEVEL',
      modulesHeader: 'MODULES',
      statusHeader: 'STATUS',
      actionsHeader: 'ACTIONS',
      noUsersFound: 'No users found',
      adjustFilters: 'Try adjusting your search or filters.',
      dbColumns: 'DB COLUMNS:',
      masterAdminDeleteError: 'The master administrator cannot be deleted.',
    },
    report: {
      title: 'COMPLIANCE REPORT',
      crossSection: 'CROSS-SECTION VIEW',
      scale: 'SCALE 1:5',
      parameters: 'CALCULATION PARAMETERS',
      totalArea: 'Total Tray Area (A_tray)',
      usedArea: 'Occupied Cable Area (Σ A_cables)',
      reserveFactor: 'Reserve Factor',
      formula: 'OCCUPANCY FORMULA',
      finalResult: 'FINAL RESULT',
      occupancyRate: 'OCCUPANCY RATE',
      approved: 'APPROVED',
      rejected: 'REJECTED',
      cableManifest: 'CABLE MANIFEST',
      total: 'TOTAL',
      units: 'UNITS',
      specification: 'SPECIFICATION',
      dimension: 'DIMENSION',
      tag: 'TAG',
      qty: 'QTY',
      printPDF: 'PRINT PDF',
      projectId: 'PROJECT ID',
      client: 'CLIENT',
      engineer: 'RESPONSIBLE ENGINEER',
      emissionDate: 'EMISSION DATE',
      digitalSignature: 'Digital Signature',
      verificationHash: 'VERIFICATION HASH',
      generatedAt: 'Generated at',
    },
    selector: {
      chooseModule: 'CHOOSE YOUR MODULE',
      cableFillDesc: 'Professional tool for calculating cable tray and conduit filling with 3D visualization.',
      capitolatoDesc: 'Automated generation of technical specifications and material books for engineering projects.',
      enter: 'ENTER MODULE',
    },
    capitolato: {
      newCapitolato: 'NEW CAPITOLATO',
      docSettings: 'DOCUMENT SETTINGS',
      projectTitle: 'PROJECT TITLE',
      docDate: 'DOCUMENT DATE',
      issuer: 'ISSUER / EMITTER',
      premise: 'PREMISE / INITIAL DESCRIPTION',
      selectCategories: 'SELECT CAPITOLATO CATEGORIES',
      totalItems: 'TOTAL ITEMS',
      estimatedPages: 'ESTIMATED SIZE',
      generatePreview: 'GENERATE PREVIEW',
      exportWord: 'EXPORT TO WORD',
      materialsLibrary: 'MATERIALS LIBRARY',
      existingProjects: 'EXISTING PROJECTS',
      noProjects: 'No projects found in database.',
      productCode: 'PRODUCT CODE',
      technicalSpecs: 'TECHNICAL SPECIFICATIONS',
      description: 'DESCRIPTION FOR CAPITOLATO',
      relatedDocs: 'RELATED DOCUMENTATION',
      personalize: 'PERSONALIZE FOR PROJECT',
      technicalSheet: 'TECHNICAL SHEET',
      projectTitleLabel: 'Project Title',
      clientName: 'Client Name',
      clientNamePlaceholder: 'Ex: Industrial Plant S.p.A.',
      docDateLabel: 'Document Date',
      issuerLabel: 'Issuer / Emitter',
      issuerPlaceholder: 'Engineer Name',
      premiseLabel: 'Premise / Initial Description',
      premisePlaceholder: 'Enter a brief technical description of the intervention...',
      selectItemsByDiscipline: 'Select Items by Discipline',
      searchItems: 'Search items...',
      selectedItems: 'Selected Items',
      code: 'Code',
      itemDescription: 'Item Description',
      referenceBrand: 'Reference Brand',
      pages: 'Pages',
      searchMaterials: 'Search materials by name or code...',
      items: 'Items',
      revision: 'Revision',
      date: 'Date',
      discipline: 'Discipline',
      executed: 'Executed',
      verified: 'Verified',
      approved: 'Approved',
      categories: {
        power: 'Power Force',
        lighting: 'Lighting',
        fire: 'Fire Alarm',
        data: 'Data / Lan Networks',
        trays: 'Cable Trays',
        solar: 'Photovoltaic',
        cctv: 'Video Surveillance',
        custom: 'Custom Category',
      },
      projectDeleted: 'Project deleted successfully.',
      deleteError: 'Error deleting project.',
      saveError: 'Error saving to database.',
      projectSaved: 'Project saved successfully.',
      imageNotAvailable: '[IMAGE NOT AVAILABLE]',
      referenceBrandLabel: 'REFERENCE BRAND/S:',
      approvedEquivalent: 'BTICINO, SCHNEIDER, ABB or approved equivalent',
    },
    misc: {
      techNotes: 'Technical Observations',
      occupancyDist: 'Occupancy Distribution',
      keyboardShortcuts: 'Keyboard Shortcuts',
      increaseProductivity: 'Increase your productivity',
      reportPreview: 'REPORT PREVIEW',
      widthShort: 'W',
      heightShort: 'H',
      threeDPreview: '3D INTERACTIVE PREVIEW',
      threeDControls: 'Use mouse to rotate and zoom',
      addCablesPrompt: 'Add cables using the form above.',
      understood: 'Understood',
      saveProjectShortcut: 'Save Project',
      newProjectShortcut: 'New Project',
      closeModalsShortcut: 'Close Modals / Reset Zoom',
    },
    cableTypes: {
      power: 'Power',
      data: 'Data',
      evac: 'EVAC',
      irai: 'IRAI',
    },
  },
  'pt-BR': {
    title: 'CableFill Pro',
    nav: {
      dashboard: 'Painel',
      trays: 'Leitos',
      conduits: 'Eletrodutos',
      cables: 'Base de Cabos',
      admin: 'ADMINISTRAÇÃO',
      users: 'Gestão de Usuários',
      newProject: 'Novo Projeto',
    },
    sidebar: {
      overview: 'VISÃO GERAL',
      cableTrays: 'ELETROCALHAS',
      conduits: 'ELETRODUTOS',
      cables: 'CABOS',
      database: 'BANCO DE PROJETOS',
      vault: 'ARQUIVO',
      documentation: 'DOCUMENTAÇÃO',
      projectManagement: 'GESTÃO DE PROJETOS',
      appSubtitle: 'SISTEMA DE ENGENHARIA',
      userTitle: 'PROPRIEDADE PRIVADA',
    },
    header: {
      currentModule: 'Módulo Atual',
      searchPlaceholder: 'BUSCAR PARÂMETROS DE ANÁLISE...',
      lightMode: 'Claro',
      darkMode: 'Escuro',
      export: 'EXPORTAR',
      exportPdf: 'EXPORTAR COMO PDF (.pdf)',
      exportCsv: 'EXPORTAR COMO EXCEL (.csv)',
      generatingPdf: 'GERANDO PDF...',
    },
    input: {
      parameters: 'PARÂMETROS DE ENTRADA',
      structureName: 'NOME DA ESTRUTURA',
      structureType: 'TIPO DE ESTRUTURA',
      dimensions: 'DIMENSÕES (mm)',
      fillLimit: 'LIMITE DE PREENCHIMENTO (%)',
      addCable: 'ADICIONAR CABO',
      calculate: 'EXECUTAR CÁLCULO',
      width: 'Largura',
      height: 'Altura',
      quantity: 'Qtd',
      standardSize: 'TAMANHO PADRÃO',
      customSize: 'CUSTOMIZADO / OUTRO',
      diameter: 'DIÂMETRO',
      size: 'DIMENSÃO (mmq)',
      tagPlaceholder: 'TAG / CIRCUITO (EX: C1, ILUM...)',
      editTag: 'EDITAR TAG...',
      hasSeparator: 'USAR SEPTO SEPARADOR',
      mixedSystemsWarning: 'CABOS DE POTÊNCIA E DADOS EXIGEM SEPTO EM ELETROCALHAS.',
      conduitMixedWarning: 'PROIBIDO MISTURAR POTÊNCIA E DADOS EM ELETRODUTOS.',
      separatorRequiredWarning: 'NÃO É POSSÍVEL DESATIVAR O SEPTO: EXISTEM CABOS DE POTÊNCIA E SISTEMAS ESPECIAIS. REMOVA UM DOS SISTEMAS PRIMEIRO.',
      clearAll: 'LIMPAR TUDO',
      cableAdded: 'Cabo adicionado',
      cableRemoved: 'Cabo removido',
      allCablesRemoved: 'Todos os cabos removidos',
      searchCables: 'BUSCAR CABOS...',
      favorites: 'FAVORITOS',
      notes: 'NOTAS DO PROJETO',
      notesPlaceholder: 'Insira notas técnicas, premissas de cálculo ou observações do projeto...',
    },
    results: {
      utilization: 'UTILIZAÇÃO',
      status: 'STATUS GLOBAL',
      pass: 'APROVADO',
      fail: 'REPROVADO',
      totalArea: 'ÁREA TOTAL',
      usedArea: 'ÁREA UTILIZADA',
      numberOfTrays: 'ESTRUTURAS NECESSÁRIAS',
      autoScaled: 'AUTO-AJUSTADO',
      deltaMax: 'DELTA MÁX',
      allow: 'LIMITE',
    },
    preview: {
      structuralPreview: 'PREVIEW ESTRUTURAL',
      crossSection: 'CORTE TRANSVERSAL',
      isometric: 'ISOMÉTRICO',
      cableSchedule: 'TABELA DE CABOS / CORRESPONDÊNCIA',
      noTag: 'SEM TAG',
      noCables: 'Nenhum cabo adicionado ao projeto ainda.',
      noSavedProjects: 'Nenhum projeto salvo encontrado.',
      structure: 'ESTRUTURA',
      limit: 'LIMITE',
      utilization: 'UTILIZAÇÃO',
      reset: 'LIMPAR PROJETO',
      newProject: 'NOVO PROJETO',
      deleteProject: 'EXCLUIR PROJETO',
      project: 'PROJETO',
      saveProject: 'SALVAR PROJETO',
      savedProjects: 'PROJETOS SALVOS',
      loadProject: 'CARREGAR PROJETO',
      lastSaved: 'ÚLTIMO SALVAMENTO',
      mustBeLoggedIn: 'Você precisa estar logado para salvar projetos.',
      saveError: 'Erro ao salvar projeto',
      unexpectedError: 'Erro inesperado ao salvar projeto',
      pdfExportError: 'Erro ao exportar PDF',
      zoomIn: 'Aumentar Zoom',
      zoomOut: 'Diminuir Zoom',
      fitToScreen: 'Ajustar à Tela',
      dashboard: 'Painel Principal',
      shortcuts: 'Atalhos',
    },
    management: {
      addNew: 'ADICIONAR NOVO MODELO',
      name: 'NOME DO MODELO',
      width: 'LARGURA (mm)',
      height: 'ALTURA (mm)',
      diameter: 'DIÂMETRO (mm)',
      weight: 'PESO (kg/km)',
      type: 'TIPO',
      category: 'CATEGORIA',
      power: 'POTÊNCIA',
      specialSystems: 'SISTEMAS ESPECIAIS (DADOS/SEGURANÇA)',
      actions: 'AÇÕES',
      save: 'SALVAR MODELO',
      cancel: 'CANCELAR',
      delete: 'EXCLUIR',
      edit: 'EDITAR',
      existingModels: 'MODELOS EXISTENTES NO BANCO',
      existingCables: 'CABOS EXISTENTES NO BANCO',
      saveSuccess: 'Modelo salvo com sucesso!',
      deleteSuccess: 'Modelo excluído com sucesso!',
      confirmDelete: 'Tem certeza que deseja excluir este modelo?',
    },
    auth: {
      login: 'LOGIN',
      register: 'CADASTRO',
      username: 'USUÁRIO',
      password: 'SENHA',
      signIn: 'ENTRAR',
      signUp: 'SOLICITAR ACESSO',
      needAccount: 'Não tem uma conta? Solicite acesso',
      haveAccount: 'Já tem uma conta? Entre aqui',
      adminPanel: 'PAINEL ADMIN',
      logout: 'SAIR',
      pendingApproval: 'Sua conta está aguardando aprovação de um administrador.',
      connectionError: 'Erro ao conectar com o servidor.',
      email: 'EMAIL',
      name: 'NOME',
      systemName: 'Rilo Elettrico',
      passwordRequired: 'A senha é obrigatória.',
    },
    userManagement: {
      title: 'GESTÃO DE USUÁRIOS',
      users: 'USUÁRIOS',
      approve: 'APROVAR',
      delete: 'EXCLUIR',
      status: 'STATUS',
      approved: 'APROVADO',
      pending: 'PENDENTE',
      role: 'FUNÇÃO',
      confirmDelete: 'Tem certeza que deseja excluir este usuário?',
      createError: 'Erro ao criar usuário',
      fetchError: 'Erro ao buscar usuários',
      approveError: 'Erro ao aprovar usuário',
      updateError: 'Erro ao atualizar usuário',
      deleteError: 'Erro ao excluir usuário',
      unknownError: 'Erro desconhecido',
      userCreated: 'Usuário criado com sucesso!',
      userApproved: 'Usuário aprovado com sucesso!',
      userDeleted: 'Usuário excluído com sucesso!',
      changesSaved: 'Alterações salvas com sucesso!',
      newUser: 'Novo Usuário',
      searchPlaceholder: 'Buscar por nome ou email...',
      allRoles: 'Todos os Níveis',
      createNewUser: 'Criar Novo Usuário',
      nameLabel: 'Nome',
      emailLabel: 'Email',
      passwordLabel: 'Senha',
      passwordRequired: 'A senha é obrigatória.',
      accessLevel: 'Nível de Acesso',
      accessibleModules: 'Módulos Acessíveis',
      cancel: 'Cancelar',
      creating: 'Criando...',
      createUser: 'Criar Usuário',
      nameHeader: 'NOME',
      emailHeader: 'EMAIL',
      levelHeader: 'NÍVEL',
      modulesHeader: 'MÓDULOS',
      statusHeader: 'STATUS',
      actionsHeader: 'AÇÕES',
      noUsersFound: 'Nenhum usuário encontrado',
      adjustFilters: 'Tente ajustar sua busca ou filtros.',
      dbColumns: 'COLUNAS NO BANCO:',
      masterAdminDeleteError: 'O administrador master não pode ser excluído.',
    },
    report: {
      title: 'RELATÓRIO DE CONFORMIDADE',
      crossSection: 'VISUALIZAÇÃO DE CORTE (CROSS-SECTION)',
      scale: 'ESCALA 1:5',
      parameters: 'PARÂMETROS DE CÁLCULO',
      totalArea: 'Área Total da Calha (A_tray)',
      usedArea: 'Área Ocupada Cabos (Σ A_cables)',
      reserveFactor: 'Fator de Reserva',
      formula: 'FÓRMULA DE OCUPAÇÃO',
      finalResult: 'RESULTADO FINAL',
      occupancyRate: 'TAXA DE OCUPAÇÃO',
      approved: 'APROVADO',
      rejected: 'REPROVADO',
      cableManifest: 'MANIFESTO DE CABOS',
      total: 'TOTAL',
      units: 'UNIDADES',
      specification: 'ESPECIFICAÇÃO',
      dimension: 'DIMENSÃO',
      tag: 'TAG',
      qty: 'QTD',
      printPDF: 'IMPRIMIR PDF',
      projectId: 'ID DO PROJETO',
      client: 'CLIENTE',
      engineer: 'ENG. RESPONSÁVEL',
      emissionDate: 'DATA DE EMISSÃO',
      digitalSignature: 'Assinatura Digital',
      verificationHash: 'HASH DE VERIFICAÇÃO',
      generatedAt: 'Gerado em',
    },
    selector: {
      chooseModule: 'ESCOLHA SEU MÓDULO',
      cableFillDesc: 'Ferramenta profissional para cálculo de preenchimento de eletrocalhas e eletrodutos com visualização 3D.',
      capitolatoDesc: 'Geração automatizada de especificações técnicas e livros de materiais para projetos de engenharia.',
      enter: 'ENTRAR NO MÓDULO',
    },
    capitolato: {
      newCapitolato: 'NOVO CAPITOLATO',
      docSettings: 'CONFIGURAÇÕES DO DOCUMENTO',
      projectTitle: 'TÍTULO DO PROJETO',
      docDate: 'DATA DO DOCUMENTO',
      issuer: 'EMISSOR / REDATOR',
      premise: 'PREMISSA / DESCRIÇÃO INICIAL',
      selectCategories: 'SELECIONAR CATEGORIAS DO CAPITOLATO',
      totalItems: 'TOTAL DE ITENS',
      estimatedPages: 'TAMANHO ESTIMADO',
      generatePreview: 'GERAR PREVIEW',
      exportWord: 'EXPORTAR PARA WORD',
      materialsLibrary: 'BIBLIOTECA DE MATERIAIS',
      existingProjects: 'PROJETOS EXISTENTES',
      noProjects: 'Nenhum projeto encontrado no banco.',
      productCode: 'CÓDIGO DO PRODUTO',
      technicalSpecs: 'ESPECIFICAÇÕES TÉCNICAS',
      description: 'DESCRIÇÃO PARA CAPITOLATO',
      relatedDocs: 'DOCUMENTAÇÃO CORRELATA',
      personalize: 'PERSONALIZAR PARA PROJETO',
      technicalSheet: 'FICHA TÉCNICA',
      projectTitleLabel: 'Título do Projeto',
      clientName: 'Nome do Cliente',
      clientNamePlaceholder: 'Ex: Indústria S.A.',
      docDateLabel: 'Data do Documento',
      issuerLabel: 'Emissor / Redator',
      issuerPlaceholder: 'Nome do Engenheiro',
      premiseLabel: 'Premissa / Descrição Inicial',
      premisePlaceholder: 'Insira uma breve descrição técnica da intervenção...',
      selectItemsByDiscipline: 'Seleção de Itens por Disciplina',
      searchItems: 'Buscar itens...',
      selectedItems: 'Itens Selecionados',
      code: 'Código',
      itemDescription: 'Descrição do Item',
      referenceBrand: 'Marca de Referência',
      pages: 'Páginas',
      searchMaterials: 'Buscar materiais por nome ou código...',
      items: 'Itens',
      revision: 'Revisão',
      date: 'Data',
      discipline: 'Disciplina',
      executed: 'Executado',
      verified: 'Verificado',
      approved: 'Aprovado',
      categories: {
        power: 'Força Motriz',
        lighting: 'Iluminação',
        fire: 'Alarme de Incêndio',
        data: 'Redes de Dados / Lan',
        trays: 'Eletrocalhas',
        solar: 'Fotovoltaico',
        cctv: 'Videomonitoramento',
        custom: 'Categoria Personalizada',
      },
      projectDeleted: 'Projeto excluído com sucesso.',
      deleteError: 'Erro ao excluir o projeto.',
      saveError: 'Erro ao salvar no banco de dados.',
      projectSaved: 'Projeto salvo com sucesso.',
      imageNotAvailable: '[IMAGEM NÃO DISPONÍVEL]',
      referenceBrandLabel: 'MARCA/S DE REFERÊNCIA:',
      approvedEquivalent: 'BTICINO, SCHNEIDER, ABB ou similar aprovado',
    },
    misc: {
      techNotes: 'Observações técnicas',
      occupancyDist: 'Distribuição de Ocupação',
      keyboardShortcuts: 'Atalhos de Teclado',
      increaseProductivity: 'Aumente sua produtividade',
      reportPreview: 'PREVIEW DO RELATÓRIO',
      widthShort: 'L',
      heightShort: 'A',
      threeDPreview: 'PREVIEW INTERATIVO 3D',
      threeDControls: 'Use o mouse para girar e dar zoom',
      addCablesPrompt: 'Adicione cabos usando o formulário acima.',
      understood: 'Entendido',
      saveProjectShortcut: 'Salvar Projeto',
      newProjectShortcut: 'Novo Projeto',
      closeModalsShortcut: 'Fechar Modais / Resetar Zoom',
    },
    cableTypes: {
      power: 'Potência',
      data: 'Dados',
      evac: 'EVAC',
      irai: 'IRAI',
    },
  },
  'it': {
    title: 'CableFill Pro',
    nav: {
      dashboard: 'Pannello',
      trays: 'Passerelle',
      conduits: 'Tubazioni',
      cables: 'Database Cavi',
      admin: 'AMMINISTRAZIONE',
      users: 'Gestione Utenti',
      newProject: 'Nuovo Progetto',
    },
    sidebar: {
      overview: 'PANORAMICA',
      cableTrays: 'PASSERELLE',
      conduits: 'TUBI PROTETTIVI',
      cables: 'CAVI',
      database: 'BANCO PROGETTI',
      vault: 'ARCHIVIO',
      documentation: 'DOCUMENTAZIONE',
      projectManagement: 'GESTIONE PROGETTI',
      appSubtitle: 'SISTEMA DI INGEGNERIA',
      userTitle: 'PROPRIETÀ PRIVATA',
    },
    header: {
      currentModule: 'Modulo Corrente',
      searchPlaceholder: 'CERCA PARAMETRI DI ANALISI...',
      lightMode: 'Chiaro',
      darkMode: 'Scuro',
      export: 'ESPORTA',
      exportPdf: 'ESPORTA COME PDF (.pdf)',
      exportCsv: 'ESPORTA COME EXCEL (.csv)',
      generatingPdf: 'GENERAZIONE PDF...',
    },
    input: {
      parameters: 'PARAMETRI DI INPUT',
      structureName: 'NOME STRUTTURA',
      structureType: 'TIPO DI STRUTTURA',
      dimensions: 'DIMENSIONI (mm)',
      fillLimit: 'LIMITE DI RIEMPIMENTO (%)',
      addCable: 'AGGIUNGI CAVO',
      calculate: 'ESEGUI CALCOLO',
      width: 'Larghezza',
      height: 'Altezza',
      quantity: 'Qtà',
      standardSize: 'DIMENSIONE STANDARD',
      customSize: 'PERSONALIZZATO / ALTRO',
      diameter: 'DIAMETRO',
      size: 'DIMENSIONE (mmq)',
      tagPlaceholder: 'TAG / CIRCUITO (ES: C1, LUCE...)',
      editTag: 'MODIFICA TAG...',
      hasSeparator: 'USA SETTO SEPARATORE',
      mixedSystemsWarning: 'CAVI POTENZA E DATI RICHIEDONO UN SETTO NELLE PASSERELLE.',
      conduitMixedWarning: 'PROIBITO MISCHIARE POTENZA E DATI NEI TUBI PROTETTIVI.',
      separatorRequiredWarning: 'NON È POSSIBILE DISATTIVARE IL SETTO: SONO PRESENTI SIA CAVI POTENZA CHE SISTEMI SPECIALI. RIMUOVERE PRIMO UN TIPO DI SISTEMA.',
      clearAll: 'PULISCI TUTTO',
      cableAdded: 'Cavo aggiunto',
      cableRemoved: 'Cavo rimosso',
      allCablesRemoved: 'Tutti i cavi rimossi',
      searchCables: 'CERCA CAVI...',
      favorites: 'PREFERITI',
      notes: 'NOTE DEL PROGETTO',
      notesPlaceholder: 'Inserire note tecniche, premesse di calcolo o osservazioni del progetto...',
    },
    results: {
      utilization: 'UTILIZZO',
      status: 'STATO GLOBALE',
      pass: 'SUPERATO',
      fail: 'FALLITO',
      totalArea: 'AREA TOTALE',
      usedArea: 'AREA UTILIZZATA',
      numberOfTrays: 'STRUTTURE NECESSARIE',
      autoScaled: 'AUTO-SCALATO',
      deltaMax: 'DELTA MAX',
      allow: 'LIMITE',
    },
    preview: {
      structuralPreview: 'ANTEPRIMA STRUTTURALE',
      crossSection: 'SEZIONE TRASVERSALE',
      isometric: 'ISOMETRICO',
      cableSchedule: 'TABELLA CAVI / CORRISPONDENZA',
      noTag: 'SENZA TAG',
      noCables: 'Nessun cavo ancora aggiunto al progetto.',
      noSavedProjects: 'Nessun progetto salvato trovato.',
      structure: 'STRUTTURA',
      limit: 'LIMITE',
      utilization: 'UTILIZZO',
      reset: 'RESET PROGETTO',
      newProject: 'NUOVO PROGETTO',
      deleteProject: 'ELIMINA PROGETTO',
      project: 'PROGETTO',
      saveProject: 'SALVA PROGETTO',
      savedProjects: 'PROGETTI SALVATI',
      loadProject: 'CARICA PROGETTO',
      lastSaved: 'ULTIMO SALVATAGGIO',
      mustBeLoggedIn: 'Devi aver effettuato l\'accesso per salvare i progetti.',
      saveError: 'Errore durante il salvataggio del progetto',
      unexpectedError: 'Errore imprevisto durante il salvataggio del progetto',
      pdfExportError: 'Errore durante l\'esportazione del PDF',
      zoomIn: 'Aumenta Zoom',
      zoomOut: 'Riduci Zoom',
      fitToScreen: 'Adatta allo Schermo',
      dashboard: 'Pannello Principale',
      shortcuts: 'Scorciatoie',
    },
    management: {
      addNew: 'AGGIUNGI NUOVO MODELLO',
      name: 'NOME MODELLO',
      width: 'LARGHEZZA (mm)',
      height: 'ALTEZZA (mm)',
      diameter: 'DIAMETRO (mm)',
      weight: 'PESO (kg/km)',
      type: 'TIPO',
      category: 'CATEGORIA',
      power: 'POTENZA',
      specialSystems: 'SISTEMI SPECIALI (DATI/SICUREZZA)',
      actions: 'AZIONI',
      save: 'SALVA MODELLO',
      cancel: 'ANNULLA',
      delete: 'ELIMINA',
      edit: 'MODIFICA',
      existingModels: 'MODELLI ESISTENTI NEL DATABASE',
      existingCables: 'CAVI ESISTENTI NEL DATABASE',
      saveSuccess: 'Modello salvato con successo!',
      deleteSuccess: 'Modello eliminato con successo!',
      confirmDelete: 'Sei sicuro di voler eliminare questo modello?',
    },
    auth: {
      login: 'LOGIN',
      register: 'REGISTRAZIONE',
      username: 'NOME UTENTE',
      password: 'PASSWORD',
      signIn: 'ACCEDI',
      signUp: 'RICHIEDI ACCESSO',
      needAccount: 'Non hai un account? Richiedi l\'accesso',
      haveAccount: 'Hai già um account? Accedi qui',
      adminPanel: 'PANNELLO ADMIN',
      logout: 'LOGOUT',
      pendingApproval: 'Il tuo account è in attesa di approvazione da parte di un amministratore.',
      connectionError: 'Errore di connessione al server.',
      email: 'EMAIL',
      name: 'NOME',
      systemName: 'Rilo Elettrico',
      passwordRequired: 'La password è obbligatoria.',
    },
    userManagement: {
      title: 'GESTIONE UTENTI',
      users: 'UTENTI',
      approve: 'APPROVA',
      delete: 'ELIMINA',
      status: 'STATO',
      approved: 'APPROVATO',
      pending: 'IN ATTESA',
      role: 'RUOLO',
      confirmDelete: 'Sei sicuro di voler eliminare questo utente?',
      createError: 'Errore durante la creazione dell\'utente',
      fetchError: 'Errore durante il recupero degli utenti',
      approveError: 'Errore durante l\'approvazione dell\'utente',
      updateError: 'Errore durante l\'aggiornamento dell\'utente',
      deleteError: 'Errore durante l\'eliminazione dell\'utente',
      unknownError: 'Errore sconosciuto',
      userCreated: 'Utente creato con successo!',
      userApproved: 'Utente approvato con successo!',
      userDeleted: 'Utente eliminato con successo!',
      changesSaved: 'Modifiche salvate con successo!',
      newUser: 'Nuovo Utente',
      searchPlaceholder: 'Cerca per nome o email...',
      allRoles: 'Tutti i Ruoli',
      createNewUser: 'Crea Nuovo Utente',
      nameLabel: 'Nome',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      passwordRequired: 'La password è obbligatoria.',
      accessLevel: 'Livello di Accesso',
      accessibleModules: 'Moduli Accessibili',
      cancel: 'Annulla',
      creating: 'Creazione...',
      createUser: 'Crea Utente',
      nameHeader: 'NOME',
      emailHeader: 'EMAIL',
      levelHeader: 'LIVELLO',
      modulesHeader: 'MODULI',
      statusHeader: 'STATO',
      actionsHeader: 'AZIONI',
      noUsersFound: 'Nessun utente trovato',
      adjustFilters: 'Prova a regolare la ricerca o i filtri.',
      dbColumns: 'COLONNE DB:',
      masterAdminDeleteError: "L'amministratore master non può essere eliminato.",
    },
    report: {
      title: 'RAPPORTO DI CONFORMITÀ',
      crossSection: 'VISTA IN SEZIONE (CROSS-SECTION)',
      scale: 'SCALA 1:5',
      parameters: 'PARAMETRI DI CALCOLO',
      totalArea: 'Area Totale Passerella (A_tray)',
      usedArea: 'Area Occupata Cavi (Σ A_cables)',
      reserveFactor: 'Fattore di Riserva',
      formula: 'FORMULA DI OCCUPAZIONE',
      finalResult: 'RISULTATO FINALE',
      occupancyRate: 'TASSO DI OCCUPAZIONE',
      approved: 'APPROVATO',
      rejected: 'RESPINTO',
      cableManifest: 'ELENCO CAVI',
      total: 'TOTALE',
      units: 'UNITÀ',
      specification: 'SPECIFICA',
      dimension: 'DIMENSIONE',
      tag: 'TAG',
      qty: 'QTÀ',
      printPDF: 'STAMPA PDF',
      projectId: 'ID PROGETTO',
      client: 'CLIENTE',
      engineer: 'ING. RESPONSABILE',
      emissionDate: 'DATA EMISSIONE',
      digitalSignature: 'Firma Digitale',
      verificationHash: 'HASH DI VERIFICA',
      generatedAt: 'Generato il',
    },
    selector: {
      chooseModule: 'SCEGLI IL TUO MODULO',
      cableFillDesc: 'Strumento professionale per il calcolo del riempimento di passerelle e tubi con visualizzazione 3D.',
      capitolatoDesc: 'Generazione automatizzata di capitolati tecnici e libri materiali per progetti di ingegneria.',
      enter: 'ENTRA NEL MODULO',
    },
    capitolato: {
      newCapitolato: 'NUOVO CAPITOLATO',
      docSettings: 'IMPOSTAZIONI DOCUMENTO',
      projectTitle: 'TITOLO DEL PROGETTO',
      docDate: 'DATA DOCUMENTO',
      issuer: 'REDATTORE / EMITTENTE',
      premise: 'PREMESSA / DESCRIZIONE INIZIALE',
      selectCategories: 'SELEZIONA CATEGORIE CAPITOLATO',
      totalItems: 'TOTALE ARTICOLI',
      estimatedPages: 'DIMENSIONE STIMATA',
      generatePreview: 'GENERA ANTEPRIMA',
      exportWord: 'ESPORTA IN WORD',
      materialsLibrary: 'ARCHIVIO MATERIALI',
      existingProjects: 'PROGETTI ESISTENTI',
      noProjects: 'Nessun progetto trovato nel database.',
      productCode: 'CODICE PRODOTTO',
      technicalSpecs: 'SPECIFICHE TECNICHE DEL MATERIALE',
      description: 'DESCRIZIONE PER CAPITOLATO',
      relatedDocs: 'DOCUMENTAZIONE CORRELATA',
      personalize: 'PERSONALIZZA PER PROGETTO',
      technicalSheet: 'SCHEDA TECNICA',
      projectTitleLabel: 'Titolo del Progetto',
      clientName: 'Nome del Cliente',
      clientNamePlaceholder: 'Es: Impianto Industriale S.p.A.',
      docDateLabel: 'Data Documento',
      issuerLabel: 'Redattore / Emittente',
      issuerPlaceholder: "Nome dell'Ingegnere",
      premiseLabel: 'Premessa / Descrizione Iniziale',
      premisePlaceholder: "Inserire una breve descrizione tecnica dell'intervento...",
      selectItemsByDiscipline: 'Selezione Articoli per Disciplina',
      searchItems: 'Cerca articoli...',
      selectedItems: 'Articoli Selezionati',
      code: 'Codice',
      itemDescription: 'Descrizione Articolo',
      referenceBrand: 'Marca Riferimento',
      pages: 'Pagine',
      searchMaterials: 'Cerca materiali per nome o codice...',
      items: 'Articoli',
      revision: 'Revisione',
      date: 'Data',
      discipline: 'Disciplina',
      executed: 'Eseguito',
      verified: 'Verificato',
      approved: 'Approvato',
      categories: {
        power: 'Forza Motrice',
        lighting: 'Illuminazione',
        fire: 'Antincendio',
        data: 'Reti Dati / Lan',
        trays: 'Passerelle',
        solar: 'Fotovoltaico',
        cctv: 'Videosorveglianza',
        custom: 'Categoria Personalizzata',
      },
      projectDeleted: 'Progetto eliminato con successo.',
      deleteError: "Errore durante l'eliminazione del progetto.",
      saveError: 'Errore durante il salvataggio su Supabase.',
      projectSaved: 'Progetto salvato con successo.',
      imageNotAvailable: '[IMMAGINE NON DISPONIBILE]',
      referenceBrandLabel: 'MARCA/CHE DI RIFERIMENTO:',
      approvedEquivalent: 'BTICINO, SCHNEIDER, ABB o simile approvato',
    },
    misc: {
      techNotes: 'Osservazioni tecniche',
      occupancyDist: 'Distribuzione Occupazione',
      keyboardShortcuts: 'Scorciatoie da Tastiera',
      increaseProductivity: 'Aumenta la tua produttività',
      reportPreview: 'ANTEPRIMA DEL RAPPORTO',
      widthShort: 'L',
      heightShort: 'H',
      threeDPreview: 'ANTEPRIMA INTERATTIVA 3D',
      threeDControls: 'Usa il mouse per ruotare e zoomare',
      addCablesPrompt: 'Aggiungi cavi usando il modulo sopra.',
      understood: 'Capito',
      saveProjectShortcut: 'Salva Progetto',
      newProjectShortcut: 'Nuovo Progetto',
      closeModalsShortcut: 'Chiudi Modal / Reset Zoom',
    },
    cableTypes: {
      power: 'Potenza',
      data: 'Dati',
      evac: 'EVAC',
      irai: 'IRAI',
    },
  }
};
