import { Cable, Translation, Language, StandardStructure, MaterialCategory, MaterialItem } from './types';

export const MATERIAL_CATEGORIES: MaterialCategory[] = [
  { id: 'cat-power', name: 'Forza Motrice', icon: 'Zap' },
  { id: 'cat-lighting', name: 'Illuminazione', icon: 'Sun' },
  { id: 'cat-fire', name: 'Antincendio', icon: 'Flame' },
  { id: 'cat-data', name: 'Reti Dati / Lan', icon: 'Network' },
  { id: 'cat-trays', name: 'Passerelle', icon: 'Layers' },
  { id: 'cat-solar', name: 'Fotovoltaico', icon: 'SunMedium' },
  { id: 'cat-cctv', name: 'Videosorveglianza', icon: 'Camera' },
];

export const MATERIAL_DATABASE: MaterialItem[] = [];

export const CABLE_DATABASE: Cable[] = [];

export const STANDARD_STRUCTURES: StandardStructure[] = [];

export const TRANSLATIONS: Record<Language, Translation> = {
  'en': {
    title: 'CableFill Pro',
    nav: {
      dashboard: 'Dashboard',
      trays: 'Cable Trays',
      conduits: 'Conduits',
      cables: 'Cables Database',
      admin: 'ADMINISTRATION',
      users: 'User Management',
      newProject: 'New Project',
    },
    sidebar: {
      overview: 'OVERVIEW',
      cableTrays: 'CABLE TRAYS',
      conduits: 'CONDUITS',
      cables: 'CABLES',
      database: 'PROJECT DATABASE',
      vault: 'VAULT',
      documentation: 'DOCUMENTATION',
      projectManagement: 'PROJECT MANAGEMENT',
      appSubtitle: 'ENGINEERING SYSTEM',
      userTitle: 'PRIVATE PROPERTY',
    },
    header: {
      currentModule: 'Current Module',
      searchPlaceholder: 'SEARCH ANALYSIS PARAMETERS...',
      lightMode: 'Light',
      darkMode: 'Dark',
      export: 'EXPORT',
      exportPdf: 'EXPORT AS PDF (.pdf)',
      exportCsv: 'EXPORT AS EXCEL (.csv)',
      generatingPdf: 'GENERATING PDF...',
    },
    input: {
      parameters: 'INPUT PARAMETERS',
      structureName: 'STRUCTURE NAME',
      structureType: 'STRUCTURE TYPE',
      dimensions: 'DIMENSIONS (mm)',
      fillLimit: 'FILL LIMIT (%)',
      addCable: 'ADD CABLE',
      calculate: 'RUN CALCULATION',
      width: 'Width',
      height: 'Height',
      quantity: 'Qty',
      standardSize: 'STANDARD SIZE',
      customSize: 'CUSTOM / OTHER',
      diameter: 'DIAMETER',
      size: 'SIZE (mmq)',
      tagPlaceholder: 'TAG / CIRCUIT (EX: C1, LIGHT...)',
      editTag: 'EDIT TAG...',
      hasSeparator: 'USE SEPARATOR (SEPTO)',
      mixedSystemsWarning: 'POWER AND DATA CABLES REQUIRE A SEPARATOR IN TRAYS.',
      conduitMixedWarning: 'MIXING POWER AND DATA CABLES IS PROHIBITED IN CONDUITS.',
      separatorRequiredWarning: 'CANNOT DISABLE SEPARATOR: BOTH POWER AND SPECIAL SYSTEMS ARE PRESENT. REMOVE ONE SYSTEM TYPE FIRST.',
      clearAll: 'CLEAR ALL',
      cableAdded: 'Cable added',
      cableRemoved: 'Cable removed',
      allCablesRemoved: 'All cables removed',
      searchCables: 'SEARCH CABLES...',
      favorites: 'FAVORITES',
      notes: 'PROJECT NOTES',
      notesPlaceholder: 'Enter technical notes, calculation assumptions or project observations...',
    },
    results: {
      utilization: 'UTILIZATION',
      status: 'GLOBAL STATUS',
      pass: 'PASS',
      fail: 'FAIL',
      totalArea: 'TOTAL AREA',
      usedArea: 'USED AREA',
      numberOfTrays: 'REQUIRED STRUCTURES',
      autoScaled: 'AUTO-SCALED',
      deltaMax: 'DELTA MAX',
      allow: 'ALLOW',
    },
    preview: {
      structuralPreview: 'STRUCTURAL PREVIEW',
      crossSection: 'CROSS-SECTION',
      isometric: 'ISOMETRIC',
      cableSchedule: 'CABLE SCHEDULE / CORRESPONDENCE',
      noTag: 'NO TAG',
      noCables: 'No cables added to project yet.',
      noSavedProjects: 'No saved projects found.',
      structure: 'STRUCTURE',
      limit: 'LIMIT',
      utilization: 'UTILIZATION',
      reset: 'RESET PROJECT',
      newProject: 'NEW PROJECT',
      deleteProject: 'DELETE PROJECT',
      project: 'PROJECT',
      saveProject: 'SAVE PROJECT',
      savedProjects: 'SAVED PROJECTS',
      loadProject: 'LOAD PROJECT',
      lastSaved: 'LAST SAVED',
      mustBeLoggedIn: 'You must be logged in to save projects.',
      saveError: 'Error saving project',
      unexpectedError: 'Unexpected error saving project',
      pdfExportError: 'Error exporting PDF',
      zoomIn: 'Zoom In',
      zoomOut: 'Zoom Out',
      fitToScreen: 'Fit to Screen',
      dashboard: 'Dashboard',
      shortcuts: 'Shortcuts',
    },
    management: {
      addNew: 'ADD NEW MODEL',
      name: 'MODEL NAME',
      width: 'Width (mm)',
      height: 'Height (mm)',
      diameter: 'DIAMETER (mm)',
      weight: 'WEIGHT (kg/km)',
      type: 'TYPE',
      category: 'CATEGORY',
      power: 'POWER',
      specialSystems: 'SPECIAL SYSTEMS (DATA/SECURITY)',
      actions: 'ACTIONS',
      save: 'SAVE MODEL',
      cancel: 'CANCEL',
      delete: 'DELETE',
      edit: 'EDIT',
      existingModels: 'EXISTING MODELS IN DATABASE',
      existingCables: 'EXISTING CABLES IN DATABASE',
      saveSuccess: 'Model saved successfully!',
      deleteSuccess: 'Model deleted successfully!',
      confirmDelete: 'Are you sure you want to delete this model?',
    },
    auth: {
      login: 'LOGIN',
      register: 'REGISTER',
      username: 'USERNAME',
      password: 'PASSWORD',
      signIn: 'SIGN IN',
      signUp: 'REQUEST ACCESS',
      needAccount: 'Need an account? Request access',
      haveAccount: 'Already have an account? Sign in',
      adminPanel: 'ADMIN PANEL',
      logout: 'LOGOUT',
      pendingApproval: 'Your account is pending approval by an administrator.',
      connectionError: 'Error connecting to the server.',
      email: 'EMAIL',
      name: 'NAME',
      systemName: 'Rilo Elettrico',
      passwordRequired: 'Password is required.',
    },
    userManagement: {
      title: 'USER MANAGEMENT',
      users: 'USERS',
      approve: 'APPROVE',
      delete: 'DELETE',
      status: 'STATUS',
      approved: 'APPROVED',
      pending: 'PENDING',
      role: 'ROLE',
      confirmDelete: 'Are you sure you want to delete this user?',
      createError: 'Error creating user',
      fetchError: 'Error fetching users',
      approveError: 'Error approving user',
      updateError: 'Error updating user',
      deleteError: 'Error deleting user',
      unknownError: 'Unknown error',
      userCreated: 'User created successfully!',
      userApproved: 'User approved successfully!',
      userDeleted: 'User deleted successfully!',
      changesSaved: 'Changes saved successfully!',
      newUser: 'New User',
      searchPlaceholder: 'Search by name or email...',
      allRoles: 'All Roles',
      createNewUser: 'Create New User',
      nameLabel: 'Name',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      passwordRequired: 'Password is required.',
      accessLevel: 'Access Level',
      accessibleModules: 'Accessible Modules',
      cancel: 'Cancel',
      creating: 'Creating...',
      createUser: 'Create User',
      nameHeader: 'NAME',
      emailHeader: 'EMAIL',
      levelHeader: 'LEVEL',
      modulesHeader: 'MODULES',
      statusHeader: 'STATUS',
      actionsHeader: 'ACTIONS',
      noUsersFound: 'No users found',
      adjustFilters: 'Try adjusting your search or filters.',
      dbColumns: 'DB COLUMNS:',
      masterAdminDeleteError: 'The master administrator cannot be deleted.',
    },
    report: {
      title: 'COMPLIANCE REPORT',
      crossSection: 'CROSS-SECTION VIEW',
      scale: 'SCALE 1:5',
      parameters: 'CALCULATION PARAMETERS',
      totalArea: 'Total Tray Area (A_tray)',
      usedArea: 'Occupied Cable Area (Σ A_cables)',
      reserveFactor: 'Reserve Factor',
      formula: 'OCCUPANCY FORMULA',
      finalResult: 'FINAL RESULT',
      occupancyRate: 'OCCUPANCY RATE',
      approved: 'APPROVED',
      rejected: 'REJECTED',
      cableManifest: 'CABLE MANIFEST',
      total: 'TOTAL',
      units: 'UNITS',
      specification: 'SPECIFICATION',
      dimension: 'DIMENSION',
      tag: 'TAG',
      qty: 'QTY',
      printPDF: 'PRINT PDF',
      projectId: 'PROJECT ID',
      client: 'CLIENT',
      engineer: 'RESPONSIBLE ENGINEER',
      emissionDate: 'EMISSION DATE',
      digitalSignature: 'Digital Signature',
      verificationHash: 'VERIFICATION HASH',
      generatedAt: 'Generated at',
    },
    selector: {
      chooseModule: 'CHOOSE YOUR MODULE',
      cableFillDesc: 'Professional tool for calculating cable tray and conduit filling with 3D visualization.',
      capitolatoDesc: 'Automated generation of technical specifications and material books for engineering projects.',
      enter: 'ENTER MODULE',
    },
    capitolato: {
      newCapitolato: 'NEW CAPITOLATO',
      docSettings: 'DOCUMENT SETTINGS',
      projectTitle: 'PROJECT TITLE',
      docDate: 'DOCUMENT DATE',
      issuer: 'ISSUER / EMITTER',
      premise: 'PREMISE / INITIAL DESCRIPTION',
      selectCategories: 'SELECT CAPITOLATO CATEGORIES',
      totalItems: 'TOTAL ITEMS',
      estimatedPages: 'ESTIMATED SIZE',
      generatePreview: 'GENERATE PREVIEW',
      exportWord: 'EXPORT TO WORD',
      materialsLibrary: 'MATERIALS LIBRARY',
      existingProjects: 'EXISTING PROJECTS',
      noProjects: 'No projects found in database.',
      productCode: 'PRODUCT CODE',
      technicalSpecs: 'TECHNICAL SPECIFICATIONS',
      description: 'DESCRIPTION FOR CAPITOLATO',
      relatedDocs: 'RELATED DOCUMENTATION',
      personalize: 'PERSONALIZE FOR PROJECT',
      technicalSheet: 'TECHNICAL SHEET',
      projectTitleLabel: 'Project Title',
      clientName: 'Client Name',
      clientNamePlaceholder: 'Ex: Industrial Plant S.p.A.',
      docDateLabel: 'Document Date',
      issuerLabel: 'Issuer / Emitter',
      issuerPlaceholder: 'Engineer Name',
      premiseLabel: 'Premise / Initial Description',
      premisePlaceholder: 'Enter a brief technical description of the intervention...',
      selectItemsByDiscipline: 'Select Items by Discipline',
      searchItems: 'Search items...',
      selectedItems: 'Selected Items',
      code: 'Code',
      itemDescription: 'Item Description',
      referenceBrand: 'Reference Brand',
      pages: 'Pages',
      searchMaterials: 'Search materials by name or code...',
      items: 'Items',
      revision: 'Revision',
      date: 'Date',
      discipline: 'Discipline',
      executed: 'Executed',
      verified: 'Verified',
      approved: 'Approved',
      categories: {
        power: 'Power Force',
        lighting: 'Lighting',
        fire: 'Fire Alarm',
        data: 'Data / Lan Networks',
        trays: 'Cable Trays',
        solar: 'Photovoltaic',
        cctv: 'Video Surveillance',
        custom: 'Custom Category',
      },
      projectDeleted: 'Project deleted successfully.',
      deleteError: 'Error deleting project.',
      saveError: 'Error saving to database.',
      projectSaved: 'Project saved successfully.',
      noRecentProjects: 'No recent projects',
      noElements: 'No elements found.',
      noTemplate: 'No Template',
      imageNotAvailable: '[IMAGE NOT AVAILABLE]',
      referenceBrandLabel: 'REFERENCE BRAND/S:',
      approvedEquivalent: 'BTICINO, SCHNEIDER, ABB or approved equivalent',
      // New translations for UI
      principal: 'PRINCIPAL',
      dashboard: 'DASHBOARD',
      projects: 'PROJECTS',
      elementsLibrary: 'ELEMENTS LIBRARY',
      userManagementNav: 'USER MANAGEMENT',
      savedProjects: 'SAVED PROJECTS',
      recentProjects: 'RECENT PROJECTS',
      viewAll: 'View All',
      technicalElementsLibrary: 'TECHNICAL ELEMENTS LIBRARY',
      editElement: 'EDIT ELEMENT',
      newElement: 'NEW TECHNICAL ELEMENT',
      preview: 'PREVIEW',
      exportToWord: 'EXPORT TO WORD',
      exporting: 'Exporting...',
      saving: 'Saving...',
      blueprintPreview: 'DOCUMENT BLUEPRINT PREVIEW',
      createNewCapitolato: 'Create New Capitolato',
      startNewDocument: 'Start a new technical document from scratch',
      // ElementLibrary translations
      searchElements: 'Search by title or brand...',
      all: 'ALL',
      elementsCount: 'elements',
      element_singular: 'element',
      element_plural: 'elements',
      noElementsMatchFilters: 'No elements match the filters.',
      noElementsYet: 'No technical elements yet. Click "New Element".',
      img: 'IMG',
      title: 'TITLE',
      category: 'CATEGORY',
      brand: 'BRAND',
      updated: 'UPDATED',
      actions: 'ACTIONS',
      edit: 'Edit',
      duplicate: 'Duplicate',
      delete: 'Delete',
      deleteElementTitle: 'Delete Element',
      deleteElementMessage: 'Are you sure you want to delete this technical element? This operation is irreversible.',
      duplicateError: 'Duplicate error: ',
      elementDuplicated: 'Element duplicated',
      deleteErrorElement: 'Delete error: ',
      elementDeleted: 'Element deleted',
      // TechnicalElementForm translations
      technicalDescription: 'Technical Description',
      dimensionalCharacteristics: 'Dimensional Characteristics',
      normativeReferences: 'Normative References',
      technicalCharacteristics: 'Technical Characteristics',
      typeOfUse: 'Type of Use',
      controlsAndTests: 'Controls and Tests',
      titleRequired: 'Title is required',
      elementSaved: 'Element saved successfully',
      hidePreview: 'Hide Preview',
      showPreview: 'Show Preview',
      generalInformation: 'General Information',
      examplePlaceholder: 'Ex. Differential Circuit Breaker',
      selectedCategory: 'Selected category:',
      imageReference: 'Image / Reference Photo',
      upload: 'Upload',
      uploading: 'Uploading...',
      chooseFile: 'Choose file',
      removeImage: 'Remove image',
      docxStructurePreview: 'DOCX Structure Preview',
      elementTitlePlaceholder: 'Element Title',
      graphicReference: 'Graphic Reference',
      noImage: 'No image',
      referenceBrandFooter: 'Reference Brand',
      // CapitolatoMetadataForm translations
      projectMetadata: 'Project Metadata',
      docxTemplate: 'DOCX Template',
      projectInfo: 'Project Information',
      docDetails: 'Document Details',
      approvalsAndSignatures: 'Approvals and Signatures',
      executedBy: 'Executed by (Author)',
      verifiedBy: 'Verified by',
      approvedBy: 'Approved by',
      importantNote: 'Important Note',
      templateKeysInfo: 'Ensure the template contains the necessary keys (e.g: {{"{{project_title}}"}}, {{"{{client}}"}}, {{"{{eseguito}}"}}, etc.).',
    },
    misc: {
      techNotes: 'Technical Observations',
      occupancyDist: 'Occupancy Distribution',
      keyboardShortcuts: 'Keyboard Shortcuts',
      increaseProductivity: 'Increase your productivity',
      reportPreview: 'REPORT PREVIEW',
      widthShort: 'W',
      heightShort: 'H',
      threeDPreview: '3D INTERACTIVE PREVIEW',
      threeDControls: 'Use mouse to rotate and zoom',
      addCablesPrompt: 'Add cables using the form above.',
      understood: 'Understood',
      saveProjectShortcut: 'Save Project',
      newProjectShortcut: 'New Project',
      closeModalsShortcut: 'Close Modals / Reset Zoom',
    },
    cableTypes: {
      power: 'Power',
      data: 'Data',
      evac: 'EVAC',
      irai: 'IRAI',
    },
    cabineMT: {
      moduleName: 'Cabine MT',
      moduleDesc: 'MV cabin earthing system calculation (CEI EN 60909 / IEC 60364-5-54)',
      inputParameters: 'INPUT PARAMETERS',
      results: 'CALCULATION RESULTS',
      numTransformers: 'NUMBER OF TRANSFORMERS',
      powerKVA: 'TRANSFORMER POWER',
      primaryVoltageKV: 'PRIMARY VOLTAGE',
      secondaryVoltageV: 'SECONDARY VOLTAGE',
      shortCircuitVoltagePct: 'SHORT-CIRCUIT VOLTAGE',
      shortCircuitVoltageDefault: 'Default: 6%',
      faultTimeS: 'FAULT CLEARING TIME',
      conductorMaterial: 'CONDUCTOR MATERIAL',
      copper: 'Copper',
      aluminum: 'Aluminum',
      totalPower: 'TOTAL INSTALLED POWER',
      shortCircuitCurrent: 'SHORT-CIRCUIT CURRENT (Icc)',
      earthingCable: 'TRANSFORMER NEUTRAL EARTHING CABLE',
      collectorBusbar: 'CABIN EARTH COLLECTOR BUSBAR',
      equipotentialBandella: 'EQUIPOTENTIAL BUSBAR (BANDELLA)',
      calculatedSection: 'Calculated',
      normalizedSection: 'Normalized (IEC 60228)',
      normativeReference: 'NORMATIVE REFERENCE',
      kFactor: 'k factor',
      unitA: 'A',
      unitMM2: 'mm²',
      unitKVA: 'kVA',
      unitKV: 'kV',
      unitV: 'V',
      unitS: 's',
      unitPct: '%',
      exportPDF: 'EXPORT PDF',
      back: 'BACK TO MODULES',
      calculating: 'Calculating...',
      noResults: 'No results yet',
      fillInputs: 'Fill in all input parameters to see the calculation results.',
      mustBePositive: 'Must be a positive value',
      invalidInput: 'Invalid value (must be between 0 and 100)',
      mustBeInteger: 'Must be a whole number',
      unitW: 'W',
      unitKW: 'kW',
      unitM: 'm',
      unitM3: 'm³',
      unitM3h: 'm³/h',
      unitBTU: 'BTU/h',
      saveProject: 'SAVE',
      newProject: 'Project',
      projectSaved: 'Project saved successfully',
      mustBeLoggedIn: 'You must be logged in to save a project',
      groundingTab: 'GROUNDING',
      ventilationTab: 'VENTILATION',
      addElement: 'ADD ELEMENT',
      thermalElements: 'THERMAL ELEMENTS',
      chooseElementType: 'Choose element type',
      transformer: 'Transformer',
      switchboardMT: 'MV Switchboard (QMT)',
      switchboardBT: 'LV Switchboard (QGBT)',
      cabineDimensions: 'CABIN DIMENSIONS',
      cabineHeight: 'HEIGHT',
      cabineWidth: 'WIDTH',
      cabineLength: 'LENGTH',
      efficiency: 'EFFICIENCY',
      dissipatedPower: 'DISSIPATED POWER',
      nominalCurrent: 'NOMINAL CURRENT',
      nominalCurrentOptional: 'optional',
      totalHeat: 'TOTAL HEAT DISSIPATED',
      btuRequired: 'COOLING REQUIRED',
      airflowRequired: 'AIRFLOW REQUIRED',
      cabineVolume: 'CABIN VOLUME',
      noElements: 'No thermal elements',
      addFirstElement: 'Click "Add Element" to add a heat source to the cabin.',
      elementLabel: 'LABEL',
      quantity: 'QUANTITY',
      editElement: 'Edit',
      removeElement: 'Remove',
      addElementTitle: 'Add Thermal Element',
      ventilationResults: 'VENTILATION RESULTS',
      thermalBreakdown: 'THERMAL BREAKDOWN',
      deltaT: 'ΔT',
      confirm: 'CONFIRM',
      cancel: 'CANCEL',
      savedProjects: 'SAVED PROJECTS',
      noSavedProjects: 'No saved projects',
      clickSaveHint: 'Click SAVE in the header to save the current project.',
      transformerSection: 'TRANSFORMER',
      protectionSection: 'PROTECTION',
      conductorSection: 'CONDUCTOR',
      /** New ventilation keys */
      thermalElementsTitle: 'THERMAL ELEMENTS (HEAT SOURCES)',
      addBtn: 'ADD',
      noneAddedMsg: 'NO ELEMENTS ADDED',
      losses: 'Losses',
      switchboardTag: 'Switchboard',
      columns: 'columns',
      dissipationPerUnit: 'Dissipation',
      totalThermalLoad: 'TOTAL THERMAL LOAD',
      usefulVolume: 'USEFUL VOLUME',
      loadBreakdownTitle: 'Load Breakdown',
      pEnvLabel: 'Environment Load (P_env)',
      pPessoasLabel: 'Occupancy Load (P_pessoas)',
      pTrafoLabel: 'Transformers Load (P_trafo)',
      pQuadrosLabel: 'Switchboards Load (P_quadros)',
      transformerType: 'Transformer',
      switchboardType: 'Switchboard (MV/LV)',
      numColumnsLabel: 'Number of Columns',
      lossesEstimateMsg: 'Estimate: 2.5% of Power',
      parametricCalcMsg: 'Parametric calculation: 0.15 kW per column/cell.',
    },
  },
  'pt-BR': {
    title: 'CableFill Pro',
    nav: {
      dashboard: 'Painel',
      trays: 'Leitos',
      conduits: 'Eletrodutos',
      cables: 'Base de Cabos',
      admin: 'ADMINISTRAÇÃO',
      users: 'Gestão de Usuários',
      newProject: 'Novo Projeto',
    },
    sidebar: {
      overview: 'VISÃO GERAL',
      cableTrays: 'ELETROCALHAS',
      conduits: 'ELETRODUTOS',
      cables: 'CABOS',
      database: 'BANCO DE PROJETOS',
      vault: 'ARQUIVO',
      documentation: 'DOCUMENTAÇÃO',
      projectManagement: 'GESTÃO DE PROJETOS',
      appSubtitle: 'SISTEMA DE ENGENHARIA',
      userTitle: 'PROPRIEDADE PRIVADA',
    },
    header: {
      currentModule: 'Módulo Atual',
      searchPlaceholder: 'BUSCAR PARÂMETROS DE ANÁLISE...',
      lightMode: 'Claro',
      darkMode: 'Escuro',
      export: 'EXPORTAR',
      exportPdf: 'EXPORTAR COMO PDF (.pdf)',
      exportCsv: 'EXPORTAR COMO EXCEL (.csv)',
      generatingPdf: 'GERANDO PDF...',
    },
    input: {
      parameters: 'PARÂMETROS DE ENTRADA',
      structureName: 'NOME DA ESTRUTURA',
      structureType: 'TIPO DE ESTRUTURA',
      dimensions: 'DIMENSÕES (mm)',
      fillLimit: 'LIMITE DE PREENCHIMENTO (%)',
      addCable: 'ADICIONAR CABO',
      calculate: 'EXECUTAR CÁLCULO',
      width: 'Largura',
      height: 'Altura',
      quantity: 'Qtd',
      standardSize: 'TAMANHO PADRÃO',
      customSize: 'CUSTOMIZADO / OUTRO',
      diameter: 'DIÂMETRO',
      size: 'DIMENSÃO (mmq)',
      tagPlaceholder: 'TAG / CIRCUITO (EX: C1, ILUM...)',
      editTag: 'EDITAR TAG...',
      hasSeparator: 'USAR SEPTO SEPARADOR',
      mixedSystemsWarning: 'CABOS DE POTÊNCIA E DADOS EXIGEM SEPTO EM ELETROCALHAS.',
      conduitMixedWarning: 'PROIBIDO MISTURAR POTÊNCIA E DADOS EM ELETRODUTOS.',
      separatorRequiredWarning: 'NÃO É POSSÍVEL DESATIVAR O SEPTO: EXISTEM CABOS DE POTÊNCIA E SISTEMAS ESPECIAIS. REMOVA UM DOS SISTEMAS PRIMEIRO.',
      clearAll: 'LIMPAR TUDO',
      cableAdded: 'Cabo adicionado',
      cableRemoved: 'Cabo removido',
      allCablesRemoved: 'Todos os cabos removidos',
      searchCables: 'BUSCAR CABOS...',
      favorites: 'FAVORITOS',
      notes: 'NOTAS DO PROJETO',
      notesPlaceholder: 'Insira notas técnicas, premissas de cálculo ou observações do projeto...',
    },
    results: {
      utilization: 'UTILIZAÇÃO',
      status: 'STATUS GLOBAL',
      pass: 'APROVADO',
      fail: 'REPROVADO',
      totalArea: 'ÁREA TOTAL',
      usedArea: 'ÁREA UTILIZADA',
      numberOfTrays: 'ESTRUTURAS NECESSÁRIAS',
      autoScaled: 'AUTO-AJUSTADO',
      deltaMax: 'DELTA MÁX',
      allow: 'LIMITE',
    },
    preview: {
      structuralPreview: 'PREVIEW ESTRUTURAL',
      crossSection: 'CORTE TRANSVERSAL',
      isometric: 'ISOMÉTRICO',
      cableSchedule: 'TABELA DE CABOS / CORRESPONDÊNCIA',
      noTag: 'SEM TAG',
      noCables: 'Nenhum cabo adicionado ao projeto ainda.',
      noSavedProjects: 'Nenhum projeto salvo encontrado.',
      structure: 'ESTRUTURA',
      limit: 'LIMITE',
      utilization: 'UTILIZAÇÃO',
      reset: 'LIMPAR PROJETO',
      newProject: 'NOVO PROJETO',
      deleteProject: 'EXCLUIR PROJETO',
      project: 'PROJETO',
      saveProject: 'SALVAR PROJETO',
      savedProjects: 'PROJETOS SALVOS',
      loadProject: 'CARREGAR PROJETO',
      lastSaved: 'ÚLTIMO SALVAMENTO',
      mustBeLoggedIn: 'Você precisa estar logado para salvar projetos.',
      saveError: 'Erro ao salvar projeto',
      unexpectedError: 'Erro inesperado ao salvar projeto',
      pdfExportError: 'Erro ao exportar PDF',
      zoomIn: 'Aumentar Zoom',
      zoomOut: 'Diminuir Zoom',
      fitToScreen: 'Ajustar à Tela',
      dashboard: 'Painel Principal',
      shortcuts: 'Atalhos',
    },
    management: {
      addNew: 'ADICIONAR NOVO MODELO',
      name: 'NOME DO MODELO',
      width: 'LARGURA (mm)',
      height: 'ALTURA (mm)',
      diameter: 'DIÂMETRO (mm)',
      weight: 'PESO (kg/km)',
      type: 'TIPO',
      category: 'CATEGORIA',
      power: 'POTÊNCIA',
      specialSystems: 'SISTEMAS ESPECIAIS (DADOS/SEGURANÇA)',
      actions: 'AÇÕES',
      save: 'SALVAR MODELO',
      cancel: 'CANCELAR',
      delete: 'EXCLUIR',
      edit: 'EDITAR',
      existingModels: 'MODELOS EXISTENTES NO BANCO',
      existingCables: 'CABOS EXISTENTES NO BANCO',
      saveSuccess: 'Modelo salvo com sucesso!',
      deleteSuccess: 'Modelo excluído com sucesso!',
      confirmDelete: 'Tem certeza que deseja excluir este modelo?',
    },
    auth: {
      login: 'LOGIN',
      register: 'CADASTRO',
      username: 'USUÁRIO',
      password: 'SENHA',
      signIn: 'ENTRAR',
      signUp: 'SOLICITAR ACESSO',
      needAccount: 'Não tem uma conta? Solicite acesso',
      haveAccount: 'Já tem uma conta? Entre aqui',
      adminPanel: 'PAINEL ADMIN',
      logout: 'SAIR',
      pendingApproval: 'Sua conta está aguardando aprovação de um administrador.',
      connectionError: 'Erro ao conectar com o servidor.',
      email: 'EMAIL',
      name: 'NOME',
      systemName: 'Rilo Elettrico',
      passwordRequired: 'A senha é obrigatória.',
    },
    userManagement: {
      title: 'GESTÃO DE USUÁRIOS',
      users: 'USUÁRIOS',
      approve: 'APROVAR',
      delete: 'EXCLUIR',
      status: 'STATUS',
      approved: 'APROVADO',
      pending: 'PENDENTE',
      role: 'FUNÇÃO',
      confirmDelete: 'Tem certeza que deseja excluir este usuário?',
      createError: 'Erro ao criar usuário',
      fetchError: 'Erro ao buscar usuários',
      approveError: 'Erro ao aprovar usuário',
      updateError: 'Erro ao atualizar usuário',
      deleteError: 'Erro ao excluir usuário',
      unknownError: 'Erro desconhecido',
      userCreated: 'Usuário criado com sucesso!',
      userApproved: 'Usuário aprovado com sucesso!',
      userDeleted: 'Usuário excluído com sucesso!',
      changesSaved: 'Alterações salvas com sucesso!',
      newUser: 'Novo Usuário',
      searchPlaceholder: 'Buscar por nome ou email...',
      allRoles: 'Todos os Níveis',
      createNewUser: 'Criar Novo Usuário',
      nameLabel: 'Nome',
      emailLabel: 'Email',
      passwordLabel: 'Senha',
      passwordRequired: 'A senha é obrigatória.',
      accessLevel: 'Nível de Acesso',
      accessibleModules: 'Módulos Acessíveis',
      cancel: 'Cancelar',
      creating: 'Criando...',
      createUser: 'Criar Usuário',
      nameHeader: 'NOME',
      emailHeader: 'EMAIL',
      levelHeader: 'NÍVEL',
      modulesHeader: 'MÓDULOS',
      statusHeader: 'STATUS',
      actionsHeader: 'AÇÕES',
      noUsersFound: 'Nenhum usuário encontrado',
      adjustFilters: 'Tente ajustar sua busca ou filtros.',
      dbColumns: 'COLUNAS NO BANCO:',
      masterAdminDeleteError: 'O administrador master não pode ser excluído.',
    },
    report: {
      title: 'RELATÓRIO DE CONFORMIDADE',
      crossSection: 'VISUALIZAÇÃO DE CORTE (CROSS-SECTION)',
      scale: 'ESCALA 1:5',
      parameters: 'PARÂMETROS DE CÁLCULO',
      totalArea: 'Área Total da Calha (A_tray)',
      usedArea: 'Área Ocupada Cabos (Σ A_cables)',
      reserveFactor: 'Fator de Reserva',
      formula: 'FÓRMULA DE OCUPAÇÃO',
      finalResult: 'RESULTADO FINAL',
      occupancyRate: 'TAXA DE OCUPAÇÃO',
      approved: 'APROVADO',
      rejected: 'REPROVADO',
      cableManifest: 'MANIFESTO DE CABOS',
      total: 'TOTAL',
      units: 'UNIDADES',
      specification: 'ESPECIFICAÇÃO',
      dimension: 'DIMENSÃO',
      tag: 'TAG',
      qty: 'QTD',
      printPDF: 'IMPRIMIR PDF',
      projectId: 'ID DO PROJETO',
      client: 'CLIENTE',
      engineer: 'ENG. RESPONSÁVEL',
      emissionDate: 'DATA DE EMISSÃO',
      digitalSignature: 'Assinatura Digital',
      verificationHash: 'HASH DE VERIFICAÇÃO',
      generatedAt: 'Gerado em',
    },
    selector: {
      chooseModule: 'ESCOLHA SEU MÓDULO',
      cableFillDesc: 'Ferramenta profissional para cálculo de preenchimento de eletrocalhas e eletrodutos com visualização 3D.',
      capitolatoDesc: 'Geração automatizada de especificações técnicas e livros de materiais para projetos de engenharia.',
      enter: 'ENTRAR NO MÓDULO',
    },
    capitolato: {
      newCapitolato: 'NOVO CAPITOLATO',
      docSettings: 'CONFIGURAÇÕES DO DOCUMENTO',
      projectTitle: 'TÍTULO DO PROJETO',
      docDate: 'DATA DO DOCUMENTO',
      issuer: 'EMISSOR / REDATOR',
      premise: 'PREMISSA / DESCRIÇÃO INICIAL',
      selectCategories: 'SELECIONAR CATEGORIAS DO CAPITOLATO',
      totalItems: 'TOTAL DE ITENS',
      estimatedPages: 'TAMANHO ESTIMADO',
      generatePreview: 'GERAR PREVIEW',
      exportWord: 'EXPORTAR PARA WORD',
      materialsLibrary: 'BIBLIOTECA DE MATERIAIS',
      existingProjects: 'PROJETOS EXISTENTES',
      noProjects: 'Nenhum projeto encontrado no banco.',
      productCode: 'CÓDIGO DO PRODUTO',
      technicalSpecs: 'ESPECIFICAÇÕES TÉCNICAS',
      description: 'DESCRIÇÃO PARA CAPITOLATO',
      relatedDocs: 'DOCUMENTAÇÃO CORRELATA',
      personalize: 'PERSONALIZAR PARA PROJETO',
      technicalSheet: 'FICHA TÉCNICA',
      projectTitleLabel: 'Título do Projeto',
      clientName: 'Nome do Cliente',
      clientNamePlaceholder: 'Ex: Indústria S.A.',
      docDateLabel: 'Data do Documento',
      issuerLabel: 'Emissor / Redator',
      issuerPlaceholder: 'Nome do Engenheiro',
      premiseLabel: 'Premissa / Descrição Inicial',
      premisePlaceholder: 'Insira uma breve descrição técnica da intervenção...',
      selectItemsByDiscipline: 'Seleção de Itens por Disciplina',
      searchItems: 'Buscar itens...',
      selectedItems: 'Itens Selecionados',
      code: 'Código',
      itemDescription: 'Descrição do Item',
      referenceBrand: 'Marca de Referência',
      pages: 'Páginas',
      searchMaterials: 'Buscar materiais por nome ou código...',
      items: 'Itens',
      revision: 'Revisão',
      date: 'Data',
      discipline: 'Disciplina',
      executed: 'Executado',
      verified: 'Verificado',
      approved: 'Aprovado',
      categories: {
        power: 'Força Motriz',
        lighting: 'Iluminação',
        fire: 'Alarme de Incêndio',
        data: 'Redes de Dados / Lan',
        trays: 'Eletrocalhas',
        solar: 'Fotovoltaico',
        cctv: 'Videomonitoramento',
        custom: 'Categoria Personalizada',
      },
      projectDeleted: 'Projeto excluído com sucesso.',
      deleteError: 'Erro ao excluir o projeto.',
      saveError: 'Erro ao salvar no banco de dados.',
      projectSaved: 'Projeto salvo com sucesso.',
      noRecentProjects: 'Nenhum projeto recente',
      noElements: 'Nenhum elemento encontrado.',
      noTemplate: 'Nenhum Modelo',
      imageNotAvailable: '[IMAGEM NÃO DISPONÍVEL]',
      referenceBrandLabel: 'MARCA/S DE REFERÊNCIA:',
      approvedEquivalent: 'BTICINO, SCHNEIDER, ABB ou similar aprovado',
      // New translations for UI
      principal: 'PRINCIPAL',
      dashboard: 'PAINEL',
      projects: 'PROJETOS',
      elementsLibrary: 'BIBLIOTECA DE ELEMENTOS',
      userManagementNav: 'GESTÃO DE USUÁRIOS',
      savedProjects: 'PROJETOS SALVOS',
      recentProjects: 'PROJETOS RECENTES',
      viewAll: 'Ver Todos',
      technicalElementsLibrary: 'BIBLIOTECA DE ELEMENTOS TÉCNICOS',
      editElement: 'EDITAR ELEMENTO',
      newElement: 'NOVO ELEMENTO TÉCNICO',
      preview: 'PREVIEW',
      exportToWord: 'EXPORTAR PARA WORD',
      exporting: 'Exportando...',
      saving: 'Salvando...',
      blueprintPreview: 'PREVIEW DO BLUEPRINT DO DOCUMENTO',
      createNewCapitolato: 'Criar Novo Capitolato',
      startNewDocument: 'Iniciar um novo documento técnico do zero',
      // ElementLibrary translations
      searchElements: 'Buscar por título ou marca...',
      all: 'TODOS',
      elementsCount: 'elementos',
      element_singular: 'elemento',
      element_plural: 'elementos',
      noElementsMatchFilters: 'Nenhum elemento corresponde aos filtros.',
      noElementsYet: 'Nenhum elemento técnico ainda. Clique em "Novo Elemento".',
      img: 'IMG',
      title: 'TÍTULO',
      category: 'CATEGORIA',
      brand: 'MARCA',
      updated: 'ATUALIZADO',
      actions: 'AÇÕES',
      edit: 'Editar',
      duplicate: 'Duplicar',
      delete: 'Excluir',
      deleteElementTitle: 'Excluir Elemento',
      deleteElementMessage: 'Tem certeza que deseja excluir este elemento técnico? Esta operação é irreversível.',
      duplicateError: 'Erro ao duplicar: ',
      elementDuplicated: 'Elemento duplicado',
      deleteErrorElement: 'Erro ao excluir: ',
      elementDeleted: 'Elemento excluído',
      // TechnicalElementForm translations
      technicalDescription: 'Descrição Técnica',
      dimensionalCharacteristics: 'Características Dimensionais',
      normativeReferences: 'Referências Normativas',
      technicalCharacteristics: 'Características Técnicas',
      typeOfUse: 'Tipo de Uso',
      controlsAndTests: 'Controles e Testes',
      titleRequired: 'Título é obrigatório',
      elementSaved: 'Elemento salvo com sucesso',
      hidePreview: 'Ocultar Preview',
      showPreview: 'Mostrar Preview',
      generalInformation: 'Informações Gerais',
      examplePlaceholder: 'Ex. Disjuntor Diferencial',
      selectedCategory: 'Categoria selecionada:',
      imageReference: 'Imagem / Foto de Referência',
      upload: 'Upload',
      uploading: 'Enviando...',
      chooseFile: 'Escolher arquivo',
      removeImage: 'Remover imagem',
      docxStructurePreview: 'Preview da Estrutura DOCX',
      elementTitlePlaceholder: 'Título do Elemento',
      graphicReference: 'Referência Gráfica',
      noImage: 'Nenhuma imagem',
      referenceBrandFooter: 'Marca de Referência',
      // CapitolatoMetadataForm translations
      projectMetadata: 'Metadados do Projeto',
      docxTemplate: 'Modelo DOCX',
      projectInfo: 'Informações do Projeto',
      docDetails: 'Detalhes do Documento',
      approvalsAndSignatures: 'Aprovações e Assinaturas',
      executedBy: 'Executado por (Autor)',
      verifiedBy: 'Verificado por',
      approvedBy: 'Aprovado por',
      importantNote: 'Nota Importante',
      templateKeysInfo: 'Certifique-se de que o modelo contém as chaves necessárias (ex: {{"{{project_title}}"}}, {{"{{client}}"}}, {{"{{eseguito}}"}}, etc.).',
    },
    misc: {
      techNotes: 'Observações técnicas',
      occupancyDist: 'Distribuição de Ocupação',
      keyboardShortcuts: 'Atalhos de Teclado',
      increaseProductivity: 'Aumente sua produtividade',
      reportPreview: 'PREVIEW DO RELATÓRIO',
      widthShort: 'L',
      heightShort: 'A',
      threeDPreview: 'PREVIEW INTERATIVO 3D',
      threeDControls: 'Use o mouse para girar e dar zoom',
      addCablesPrompt: 'Adicione cabos usando o formulário acima.',
      understood: 'Entendido',
      saveProjectShortcut: 'Salvar Projeto',
      newProjectShortcut: 'Novo Projeto',
      closeModalsShortcut: 'Fechar Modais / Resetar Zoom',
    },
    cableTypes: {
      power: 'Potência',
      data: 'Dados',
      evac: 'EVAC',
      irai: 'IRAI',
    },
    cabineMT: {
      moduleName: 'Cabine MT',
      moduleDesc: 'Cálculo do sistema de aterramento de cabine de Média Tensão (CEI EN 60909 / IEC 60364-5-54)',
      inputParameters: 'PARÂMETROS DE ENTRADA',
      results: 'RESULTADOS DO CÁLCULO',
      numTransformers: 'QUANTIDADE DE TRANSFORMADORES',
      powerKVA: 'POTÊNCIA DO TRANSFORMADOR',
      primaryVoltageKV: 'TENSÃO PRIMÁRIA',
      secondaryVoltageV: 'TENSÃO SECUNDÁRIA',
      shortCircuitVoltagePct: 'TENSÃO DE CURTO-CIRCUITO (Ucc%)',
      shortCircuitVoltageDefault: 'Padrão: 6%',
      faultTimeS: 'TEMPO DE ATUAÇÃO DA PROTEÇÃO',
      conductorMaterial: 'MATERIAL DO CONDUTOR',
      copper: 'Cobre',
      aluminum: 'Alumínio',
      totalPower: 'POTÊNCIA TOTAL INSTALADA',
      shortCircuitCurrent: 'CORRENTE DE CURTO-CIRCUITO (Icc)',
      earthingCable: 'CABO DE ATERRAMENTO DO NEUTRO DO TRANSFORMADOR',
      collectorBusbar: 'COLETOR DE TERRA DA CABINE',
      equipotentialBandella: 'BANDELLA DE EQUIPOTENCIALIZAÇÃO',
      calculatedSection: 'Calculado',
      normalizedSection: 'Normalizado (IEC 60228)',
      normativeReference: 'REFERÊNCIA NORMATIVA',
      kFactor: 'Fator k',
      unitA: 'A',
      unitMM2: 'mm²',
      unitKVA: 'kVA',
      unitKV: 'kV',
      unitV: 'V',
      unitS: 's',
      unitPct: '%',
      exportPDF: 'EXPORTAR PDF',
      back: 'VOLTAR AOS MÓDULOS',
      calculating: 'Calculando...',
      noResults: 'Sem resultados ainda',
      fillInputs: 'Preencha todos os parâmetros de entrada para visualizar os resultados do cálculo.',
      mustBePositive: 'Deve ser um valor positivo',
      invalidInput: 'Valor inválido (deve estar entre 0 e 100)',
      mustBeInteger: 'Deve ser um número inteiro',
      unitW: 'W',
      unitKW: 'kW',
      unitM: 'm',
      unitM3: 'm³',
      unitM3h: 'm³/h',
      unitBTU: 'BTU/h',
      saveProject: 'SALVAR',
      newProject: 'Projeto',
      projectSaved: 'Projeto salvo com sucesso',
      mustBeLoggedIn: 'Você precisa estar conectado para salvar um projeto',
      groundingTab: 'ATERRAMENTO',
      ventilationTab: 'VENTILAÇÃO',
      addElement: 'ADICIONAR ELEMENTO',
      thermalElements: 'ELEMENTOS TÉRMICOS',
      chooseElementType: 'Escolha o tipo de elemento',
      transformer: 'Transformador',
      switchboardMT: 'Quadro de Média Tensão (QMT)',
      switchboardBT: 'Quadro de Baixa Tensão (QGBT)',
      cabineDimensions: 'DIMENSÕES DA CABINE',
      cabineHeight: 'ALTURA',
      cabineWidth: 'LARGURA',
      cabineLength: 'COMPRIMENTO',
      efficiency: 'RENDIMENTO',
      dissipatedPower: 'POTÊNCIA DISSIPADA',
      nominalCurrent: 'CORRENTE NOMINAL',
      nominalCurrentOptional: 'opcional',
      totalHeat: 'CALOR TOTAL DISSIPADO',
      btuRequired: 'CLIMATIZAÇÃO NECESSÁRIA',
      airflowRequired: 'PORTATA DE AR NECESSÁRIA',
      cabineVolume: 'VOLUME DA CABINE',
      noElements: 'Nenhum elemento térmico',
      addFirstElement: 'Clique em “Adicionar Elemento” para incluir uma fonte de calor.',
      elementLabel: 'IDENTIFICAÇÃO',
      quantity: 'QUANTIDADE',
      editElement: 'Editar',
      removeElement: 'Remover',
      addElementTitle: 'Adicionar Elemento Térmico',
      ventilationResults: 'RESULTADOS DE VENTILAÇÃO',
      thermalBreakdown: 'DETALHAMENTO TÉRMICO',
      deltaT: 'ΔT',
      confirm: 'CONFIRMAR',
      cancel: 'CANCELAR',
      savedProjects: 'PROJETOS SALVOS',
      noSavedProjects: 'Nenhum projeto salvo',
      clickSaveHint: 'Clique em SALVAR no cabeçalho para salvar o projeto atual.',
      transformerSection: 'TRANSFORMADOR',
      protectionSection: 'PROTEÇÃO',
      conductorSection: 'CONDUTOR',
      /** New ventilation keys */
      thermalElementsTitle: 'ELEMENTOS TÉRMICOS (FONTES DE CALOR)',
      addBtn: 'ADICIONAR',
      noneAddedMsg: 'NENHUM ELEMENTO ADICIONADO',
      losses: 'Perdas',
      switchboardTag: 'Quadro',
      columns: 'colunas',
      dissipationPerUnit: 'Dissipação',
      totalThermalLoad: 'CARGA TÉRMICA TOTAL',
      usefulVolume: 'VOLUME ÚTIL',
      loadBreakdownTitle: 'Discriminação de Cargas',
      pEnvLabel: 'Carga Envoltória (P_env)',
      pPessoasLabel: 'Carga Ocupação (P_pessoas)',
      pTrafoLabel: 'Carga Transformadores (P_trafo)',
      pQuadrosLabel: 'Carga Quadros (P_quadros)',
      transformerType: 'Transformador',
      switchboardType: 'Quadro (MT/BT)',
      numColumnsLabel: 'Quantidade de Colunas',
      lossesEstimateMsg: 'Estimativa: 2.5% da Potência',
      parametricCalcMsg: 'Cálculo paramétrico: 0.15 kW por coluna/célula.',
    },
  },
  'it': {
    title: 'CableFill Pro',
    nav: {
      dashboard: 'Pannello',
      trays: 'Passerelle',
      conduits: 'Tubazioni',
      cables: 'Database Cavi',
      admin: 'AMMINISTRAZIONE',
      users: 'Gestione Utenti',
      newProject: 'Nuovo Progetto',
    },
    sidebar: {
      overview: 'PANORAMICA',
      cableTrays: 'PASSERELLE',
      conduits: 'TUBI PROTETTIVI',
      cables: 'CAVI',
      database: 'BANCO PROGETTI',
      vault: 'ARCHIVIO',
      documentation: 'DOCUMENTAZIONE',
      projectManagement: 'GESTIONE PROGETTI',
      appSubtitle: 'SISTEMA DI INGEGNERIA',
      userTitle: 'PROPRIETÀ PRIVATA',
    },
    header: {
      currentModule: 'Modulo Corrente',
      searchPlaceholder: 'CERCA PARAMETRI DI ANALISI...',
      lightMode: 'Chiaro',
      darkMode: 'Scuro',
      export: 'ESPORTA',
      exportPdf: 'ESPORTA COME PDF (.pdf)',
      exportCsv: 'ESPORTA COME EXCEL (.csv)',
      generatingPdf: 'GENERAZIONE PDF...',
    },
    input: {
      parameters: 'PARAMETRI DI INPUT',
      structureName: 'NOME STRUTTURA',
      structureType: 'TIPO DI STRUTTURA',
      dimensions: 'DIMENSIONI (mm)',
      fillLimit: 'LIMITE DI RIEMPIMENTO (%)',
      addCable: 'AGGIUNGI CAVO',
      calculate: 'ESEGUI CALCOLO',
      width: 'Larghezza',
      height: 'Altezza',
      quantity: 'Qtà',
      standardSize: 'DIMENSIONE STANDARD',
      customSize: 'PERSONALIZZATO / ALTRO',
      diameter: 'DIAMETRO',
      size: 'DIMENSIONE (mmq)',
      tagPlaceholder: 'TAG / CIRCUITO (ES: C1, LUCE...)',
      editTag: 'MODIFICA TAG...',
      hasSeparator: 'USA SETTO SEPARATORE',
      mixedSystemsWarning: 'CAVI POTENZA E DATI RICHIEDONO UN SETTO NELLE PASSERELLE.',
      conduitMixedWarning: 'PROIBITO MISCHIARE POTENZA E DATI NEI TUBI PROTETTIVI.',
      separatorRequiredWarning: 'NON È POSSIBILE DISATTIVARE IL SETTO: SONO PRESENTI SIA CAVI POTENZA CHE SISTEMI SPECIALI. RIMUOVERE PRIMO UN TIPO DI SISTEMA.',
      clearAll: 'PULISCI TUTTO',
      cableAdded: 'Cavo aggiunto',
      cableRemoved: 'Cavo rimosso',
      allCablesRemoved: 'Tutti i cavi rimossi',
      searchCables: 'CERCA CAVI...',
      favorites: 'PREFERITI',
      notes: 'NOTE DEL PROGETTO',
      notesPlaceholder: 'Inserire note tecniche, premesse di calcolo o osservazioni del progetto...',
    },
    results: {
      utilization: 'UTILIZZO',
      status: 'STATO GLOBALE',
      pass: 'SUPERATO',
      fail: 'FALLITO',
      totalArea: 'AREA TOTALE',
      usedArea: 'AREA UTILIZZATA',
      numberOfTrays: 'STRUTTURE NECESSARIE',
      autoScaled: 'AUTO-SCALATO',
      deltaMax: 'DELTA MAX',
      allow: 'LIMITE',
    },
    preview: {
      structuralPreview: 'ANTEPRIMA STRUTTURALE',
      crossSection: 'SEZIONE TRASVERSALE',
      isometric: 'ISOMETRICO',
      cableSchedule: 'TABELLA CAVI / CORRISPONDENZA',
      noTag: 'SENZA TAG',
      noCables: 'Nessun cavo ancora aggiunto al progetto.',
      noSavedProjects: 'Nessun progetto salvato trovato.',
      structure: 'STRUTTURA',
      limit: 'LIMITE',
      utilization: 'UTILIZZO',
      reset: 'RESET PROGETTO',
      newProject: 'NUOVO PROGETTO',
      deleteProject: 'ELIMINA PROGETTO',
      project: 'PROGETTO',
      saveProject: 'SALVA PROGETTO',
      savedProjects: 'PROGETTI SALVATI',
      loadProject: 'CARICA PROGETTO',
      lastSaved: 'ULTIMO SALVATAGGIO',
      mustBeLoggedIn: 'Devi aver effettuato l\'accesso per salvare i progetti.',
      saveError: 'Errore durante il salvataggio del progetto',
      unexpectedError: 'Errore imprevisto durante il salvataggio del progetto',
      pdfExportError: 'Errore durante l\'esportazione del PDF',
      zoomIn: 'Aumenta Zoom',
      zoomOut: 'Riduci Zoom',
      fitToScreen: 'Adatta allo Schermo',
      dashboard: 'Pannello Principale',
      shortcuts: 'Scorciatoie',
    },
    management: {
      addNew: 'AGGIUNGI NUOVO MODELLO',
      name: 'NOME MODELLO',
      width: 'LARGHEZZA (mm)',
      height: 'ALTEZZA (mm)',
      diameter: 'DIAMETRO (mm)',
      weight: 'PESO (kg/km)',
      type: 'TIPO',
      category: 'CATEGORIA',
      power: 'POTENZA',
      specialSystems: 'SISTEMI SPECIALI (DATI/SICUREZZA)',
      actions: 'AZIONI',
      save: 'SALVA MODELLO',
      cancel: 'ANNULLA',
      delete: 'ELIMINA',
      edit: 'MODIFICA',
      existingModels: 'MODELLI ESISTENTI NEL DATABASE',
      existingCables: 'CAVI ESISTENTI NEL DATABASE',
      saveSuccess: 'Modello salvato con successo!',
      deleteSuccess: 'Modello eliminato con successo!',
      confirmDelete: 'Sei sicuro di voler eliminare questo modello?',
    },
    auth: {
      login: 'LOGIN',
      register: 'REGISTRAZIONE',
      username: 'NOME UTENTE',
      password: 'PASSWORD',
      signIn: 'ACCEDI',
      signUp: 'RICHIEDI ACCESSO',
      needAccount: 'Non hai un account? Richiedi l\'accesso',
      haveAccount: 'Hai già um account? Accedi qui',
      adminPanel: 'PANNELLO ADMIN',
      logout: 'LOGOUT',
      pendingApproval: 'Il tuo account è in attesa di approvazione da parte di un amministratore.',
      connectionError: 'Errore di connessione al server.',
      email: 'EMAIL',
      name: 'NOME',
      systemName: 'Rilo Elettrico',
      passwordRequired: 'La password è obbligatoria.',
    },
    userManagement: {
      title: 'GESTIONE UTENTI',
      users: 'UTENTI',
      approve: 'APPROVA',
      delete: 'ELIMINA',
      status: 'STATO',
      approved: 'APPROVATO',
      pending: 'IN ATTESA',
      role: 'RUOLO',
      confirmDelete: 'Sei sicuro di voler eliminare questo utente?',
      createError: 'Errore durante la creazione dell\'utente',
      fetchError: 'Errore durante il recupero degli utenti',
      approveError: 'Errore durante l\'approvazione dell\'utente',
      updateError: 'Errore durante l\'aggiornamento dell\'utente',
      deleteError: 'Errore durante l\'eliminazione dell\'utente',
      unknownError: 'Errore sconosciuto',
      userCreated: 'Utente creato con successo!',
      userApproved: 'Utente approvato con successo!',
      userDeleted: 'Utente eliminato con successo!',
      changesSaved: 'Modifiche salvate con successo!',
      newUser: 'Nuovo Utente',
      searchPlaceholder: 'Cerca per nome o email...',
      allRoles: 'Tutti i Ruoli',
      createNewUser: 'Crea Nuovo Utente',
      nameLabel: 'Nome',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      passwordRequired: 'La password è obbligatoria.',
      accessLevel: 'Livello di Accesso',
      accessibleModules: 'Moduli Accessibili',
      cancel: 'Annulla',
      creating: 'Creazione...',
      createUser: 'Crea Utente',
      nameHeader: 'NOME',
      emailHeader: 'EMAIL',
      levelHeader: 'LIVELLO',
      modulesHeader: 'MODULI',
      statusHeader: 'STATO',
      actionsHeader: 'AZIONI',
      noUsersFound: 'Nessun utente trovato',
      adjustFilters: 'Prova a regolare la ricerca o i filtri.',
      dbColumns: 'COLONNE DB:',
      masterAdminDeleteError: "L'amministratore master non può essere eliminato.",
    },
    report: {
      title: 'RAPPORTO DI CONFORMITÀ',
      crossSection: 'VISTA IN SEZIONE (CROSS-SECTION)',
      scale: 'SCALA 1:5',
      parameters: 'PARAMETRI DI CALCOLO',
      totalArea: 'Area Totale Passerella (A_tray)',
      usedArea: 'Area Occupata Cavi (Σ A_cables)',
      reserveFactor: 'Fattore di Riserva',
      formula: 'FORMULA DI OCCUPAZIONE',
      finalResult: 'RISULTATO FINALE',
      occupancyRate: 'TASSO DI OCCUPAZIONE',
      approved: 'APPROVATO',
      rejected: 'RESPINTO',
      cableManifest: 'ELENCO CAVI',
      total: 'TOTALE',
      units: 'UNITÀ',
      specification: 'SPECIFICA',
      dimension: 'DIMENSIONE',
      tag: 'TAG',
      qty: 'QTÀ',
      printPDF: 'STAMPA PDF',
      projectId: 'ID PROGETTO',
      client: 'CLIENTE',
      engineer: 'ING. RESPONSABILE',
      emissionDate: 'DATA EMISSIONE',
      digitalSignature: 'Firma Digitale',
      verificationHash: 'HASH DI VERIFICA',
      generatedAt: 'Generato il',
    },
    selector: {
      chooseModule: 'SCEGLI IL TUO MODULO',
      cableFillDesc: 'Strumento professionale per il calcolo del riempimento di passerelle e tubi con visualizzazione 3D.',
      capitolatoDesc: 'Generazione automatizzata di capitolati tecnici e libri materiali per progetti di ingegneria.',
      enter: 'ENTRA NEL MODULO',
    },
    capitolato: {
      newCapitolato: 'NUOVO CAPITOLATO',
      docSettings: 'IMPOSTAZIONI DOCUMENTO',
      projectTitle: 'TITOLO DEL PROGETTO',
      docDate: 'DATA DOCUMENTO',
      issuer: 'REDATTORE / EMITTENTE',
      premise: 'PREMESSA / DESCRIZIONE INIZIALE',
      selectCategories: 'SELEZIONA CATEGORIE CAPITOLATO',
      totalItems: 'TOTALE ARTICOLI',
      estimatedPages: 'DIMENSIONE STIMATA',
      generatePreview: 'GENERA ANTEPRIMA',
      exportWord: 'ESPORTA IN WORD',
      materialsLibrary: 'ARCHIVIO MATERIALI',
      existingProjects: 'PROGETTI ESISTENTI',
      noProjects: 'Nessun progetto trovato nel database.',
      productCode: 'CODICE PRODOTTO',
      technicalSpecs: 'SPECIFICHE TECNICHE DEL MATERIALE',
      description: 'DESCRIZIONE PER CAPITOLATO',
      relatedDocs: 'DOCUMENTAZIONE CORRELATA',
      personalize: 'PERSONALIZZA PER PROGETTO',
      technicalSheet: 'SCHEDA TECNICA',
      projectTitleLabel: 'Titolo del Progetto',
      clientName: 'Nome del Cliente',
      clientNamePlaceholder: 'Es: Impianto Industriale S.p.A.',
      docDateLabel: 'Data Documento',
      issuerLabel: 'Redattore / Emittente',
      issuerPlaceholder: "Nome dell'Ingegnere",
      premiseLabel: 'Premessa / Descrizione Iniziale',
      premisePlaceholder: "Inserire una breve descrizione tecnica dell'intervento...",
      selectItemsByDiscipline: 'Selezione Articoli per Disciplina',
      searchItems: 'Cerca articoli...',
      selectedItems: 'Articoli Selezionati',
      code: 'Codice',
      itemDescription: 'Descrizione Articolo',
      referenceBrand: 'Marca Riferimento',
      pages: 'Pagine',
      searchMaterials: 'Cerca materiali per nome o codice...',
      items: 'Articoli',
      revision: 'Revisione',
      date: 'Data',
      discipline: 'Disciplina',
      executed: 'Eseguito',
      verified: 'Verificato',
      approved: 'Approvato',
      categories: {
        power: 'Forza Motrice',
        lighting: 'Illuminazione',
        fire: 'Antincendio',
        data: 'Reti Dati / Lan',
        trays: 'Passerelle',
        solar: 'Fotovoltaico',
        cctv: 'Videosorveglianza',
        custom: 'Categoria Personalizzata',
      },
      projectDeleted: 'Progetto eliminato con successo.',
      deleteError: "Errore durante l'eliminazione del progetto.",
      saveError: 'Errore durante il salvataggio su Supabase.',
      projectSaved: 'Progetto salvato con successo.',
      noRecentProjects: 'Nessun progetto recente',
      noElements: 'Nessun elemento trovato.',
      noTemplate: 'Nessun Modello',
      imageNotAvailable: '[IMMAGINE NON DISPONIBILE]',
      referenceBrandLabel: 'MARCA/CHE DI RIFERIMENTO:',
      approvedEquivalent: 'BTICINO, SCHNEIDER, ABB o simile approvato',
      // New translations for UI
      principal: 'PRINCIPALE',
      dashboard: 'DASHBOARD',
      projects: 'PROGETTI',
      elementsLibrary: 'LIBRERIA ELEMENTI',
      userManagementNav: 'GESTIONE UTENTI',
      savedProjects: 'PROGETTI SALVATI',
      recentProjects: 'PROGETTI RECENTI',
      viewAll: 'Vedi tutti',
      technicalElementsLibrary: 'LIBRERIA ELEMENTI TECNICI',
      editElement: 'MODIFICA ELEMENTO',
      newElement: 'NUOVO ELEMENTO TECNICO',
      preview: 'ANTEPRIMA',
      exportToWord: 'ESPORTA IN WORD',
      exporting: 'Esportazione...',
      saving: 'Salvataggio...',
      blueprintPreview: 'ANTEPRIMA BLUEPRINT DOCUMENTO',
      createNewCapitolato: 'Crea Nuovo Capitolato',
      startNewDocument: 'Inizia un nuovo documento tecnico da zero',
      // ElementLibrary translations
      searchElements: 'Cerca per titolo o marca...',
      all: 'TUTTI',
      elementsCount: 'elementi',
      element_singular: 'elemento',
      element_plural: 'elementi',
      noElementsMatchFilters: 'Nessun elemento corrisponde ai filtri.',
      noElementsYet: 'Nessun elemento tecnico ancora. Clicca "Nuovo Elemento".',
      img: 'IMG',
      title: 'TITOLO',
      category: 'CATEGORIA',
      brand: 'MARCA',
      updated: 'AGGIORNATO',
      actions: 'AZIONI',
      edit: 'Modifica',
      duplicate: 'Duplica',
      delete: 'Elimina',
      deleteElementTitle: 'Elimina Elemento',
      deleteElementMessage: 'Sei sicuro di voler eliminare questo elemento tecnico? L\'operazione è irreversibile.',
      duplicateError: 'Errore duplicazione: ',
      elementDuplicated: 'Elemento duplicato',
      deleteErrorElement: 'Errore eliminazione: ',
      elementDeleted: 'Elemento eliminato',
      // TechnicalElementForm translations
      technicalDescription: 'Descrizione Tecnica',
      dimensionalCharacteristics: 'Caratteristiche Dimensionali',
      normativeReferences: 'Riferimenti Normativi',
      technicalCharacteristics: 'Caratteristiche Tecniche',
      typeOfUse: 'Tipo di Impiego',
      controlsAndTests: 'Controlli e Collaudi',
      titleRequired: 'Il titolo è obbligatorio',
      elementSaved: 'Elemento salvato con successo',
      hidePreview: 'Nascondi Anteprima',
      showPreview: 'Mostra Anteprima',
      generalInformation: 'Informazioni Generali',
      examplePlaceholder: 'Es. Interruttore Magnetotermico Differenziale',
      selectedCategory: 'Categoria selezionata:',
      imageReference: 'Immagine / Foto di Riferimento',
      upload: 'Upload',
      uploading: 'Caricamento...',
      chooseFile: 'Scegli file',
      removeImage: 'Rimuovi immagine',
      docxStructurePreview: 'Anteprima Struttura DOCX',
      elementTitlePlaceholder: 'Titolo Elemento',
      graphicReference: 'Riferimento Grafico',
      noImage: 'Nessuna immagine',
      referenceBrandFooter: 'Marca di Riferimento',
      // CapitolatoMetadataForm translations
      projectMetadata: 'Metadata Progetto',
      docxTemplate: 'Template DOCX',
      projectInfo: 'Informazioni Progetto',
      docDetails: 'Dettagli Documento',
      approvalsAndSignatures: 'Approvazioni e Firme',
      executedBy: 'Eseguito da (Redattore)',
      verifiedBy: 'Verificato da',
      approvedBy: 'Approvato da',
      importantNote: 'Nota Importante',
      templateKeysInfo: "Assicurati che il template contenga le chiavi necessarie (es: {\"{{project_title}}\"}, {\"{{client}}\"}, {\"{{eseguito}}\"}, ecc.).",
    },
    misc: {
      techNotes: 'Osservazioni tecniche',
      occupancyDist: 'Distribuzione Occupazione',
      keyboardShortcuts: 'Scorciatoie da Tastiera',
      increaseProductivity: 'Aumenta la tua produttività',
      reportPreview: 'ANTEPRIMA DEL RAPPORTO',
      widthShort: 'L',
      heightShort: 'H',
      threeDPreview: 'ANTEPRIMA INTERATTIVA 3D',
      threeDControls: 'Usa il mouse per ruotare e zoomare',
      addCablesPrompt: 'Aggiungi cavi usando il modulo sopra.',
      understood: 'Capito',
      saveProjectShortcut: 'Salva Progetto',
      newProjectShortcut: 'Nuovo Progetto',
      closeModalsShortcut: 'Chiudi Modal / Reset Zoom',
    },
    cableTypes: {
      power: 'Potenza',
      data: 'Dati',
      evac: 'EVAC',
      irai: 'IRAI',
    },
    cabineMT: {
      moduleName: 'Cabina MT',
      moduleDesc: 'Calcolo sistema di messa a terra cabina Media Tensione (CEI EN 60909 / IEC 60364-5-54)',
      inputParameters: 'PARAMETRI DI INPUT',
      results: 'RISULTATI DEL CALCOLO',
      numTransformers: 'NUMERO DI TRASFORMATORI',
      powerKVA: 'POTENZA DEL TRASFORMATORE',
      primaryVoltageKV: 'TENSIONE PRIMARIA',
      secondaryVoltageV: 'TENSIONE SECONDARIA',
      shortCircuitVoltagePct: 'TENSIONE DI CORTOCIRCUITO (Ucc%)',
      shortCircuitVoltageDefault: 'Default: 6%',
      faultTimeS: 'TEMPO DI INTERVENTO DELLA PROTEZIONE',
      conductorMaterial: 'MATERIALE DEL CONDUTTORE',
      copper: 'Rame',
      aluminum: 'Alluminio',
      totalPower: 'POTENZA TOTALE INSTALLATA',
      shortCircuitCurrent: 'CORRENTE DI CORTOCIRCUITO (Icc)',
      earthingCable: 'CAVO DI TERRA DEL NEUTRO DEL TRASFORMATORE',
      collectorBusbar: 'COLLETTORE DI TERRA DELLA CABINA',
      equipotentialBandella: 'BANDELLA DI EQUIPOTENZIALIZZAZIONE',
      calculatedSection: 'Calcolato',
      normalizedSection: 'Normalizzato (IEC 60228)',
      normativeReference: 'RIFERIMENTO NORMATIVO',
      kFactor: 'Fattore k',
      unitA: 'A',
      unitMM2: 'mm²',
      unitKVA: 'kVA',
      unitKV: 'kV',
      unitV: 'V',
      unitS: 's',
      unitPct: '%',
      exportPDF: 'ESPORTA PDF',
      back: 'TORNA AI MODULI',
      calculating: 'Calcolo in corso...',
      noResults: 'Nessun risultato ancora',
      fillInputs: 'Compila tutti i parametri di input per visualizzare i risultati del calcolo.',
      mustBePositive: 'Deve essere un valore positivo',
      invalidInput: 'Valore non valido (deve essere compreso tra 0 e 100)',
      mustBeInteger: 'Deve essere un numero intero',
      unitW: 'W',
      unitKW: 'kW',
      unitM: 'm',
      unitM3: 'm³',
      unitM3h: 'm³/h',
      unitBTU: 'BTU/h',
      saveProject: 'SALVA',
      newProject: 'Progetto',
      projectSaved: 'Progetto salvato con successo',
      mustBeLoggedIn: 'Devi essere connesso per salvare un progetto',
      groundingTab: 'MESSA A TERRA',
      ventilationTab: 'VENTILAZIONE',
      addElement: 'AGGIUNGI ELEMENTO',
      thermalElements: 'ELEMENTI TERMICI',
      chooseElementType: 'Scegli il tipo di elemento',
      transformer: 'Trasformatore',
      switchboardMT: 'Quadro di Media Tensione (QMT)',
      switchboardBT: 'Quadro di Bassa Tensione (QGBT)',
      cabineDimensions: 'DIMENSIONI DELLA CABINA',
      cabineHeight: 'ALTEZZA',
      cabineWidth: 'LARGHEZZA',
      cabineLength: 'PROFONDITÀ',
      efficiency: 'RENDIMENTO',
      dissipatedPower: 'POTENZA DISSIPATA',
      nominalCurrent: 'CORRENTE NOMINALE',
      nominalCurrentOptional: 'opzionale',
      totalHeat: 'CALORE TOTALE DISSIPATO',
      btuRequired: 'CLIMATIZZAZIONE NECESSARIA',
      airflowRequired: 'PORTATA D\'ARIA NECESSARIA',
      cabineVolume: 'VOLUME CABINA',
      noElements: 'Nessun elemento termico',
      addFirstElement: 'Clicca "Aggiungi Elemento" per aggiungere una sorgente di calore.',
      elementLabel: 'ETICHETTA',
      quantity: 'QUANTITÀ',
      editElement: 'Modifica',
      removeElement: 'Rimuovi',
      addElementTitle: 'Aggiungi Elemento Termico',
      ventilationResults: 'RISULTATI DI VENTILAZIONE',
      thermalBreakdown: 'DETTAGLIO TERMICO',
      deltaT: 'ΔT',
      confirm: 'CONFERMA',
      cancel: 'ANNULLA',
      savedProjects: 'PROGETTI SALVATI',
      noSavedProjects: 'Nessun progetto salvato',
      clickSaveHint: 'Clicca SALVA nell\'intestazione per salvare il progetto corrente.',
      transformerSection: 'TRASFORMATORE',
      protectionSection: 'PROTEZIONE',
      conductorSection: 'CONDUTTORE',
      /** New ventilation keys */
      thermalElementsTitle: 'ELEMENTI TERMICI (SORGENTI DI CALORE)',
      addBtn: 'AGGIUNGI',
      noneAddedMsg: 'NESSUN ELEMENTO AGGIUNTO',
      losses: 'Perdite',
      switchboardTag: 'Quadro',
      columns: 'colonne',
      dissipationPerUnit: 'Dissipazione',
      totalThermalLoad: 'CARICO TERMICO TOTALE',
      usefulVolume: 'VOLUME UTILE',
      loadBreakdownTitle: 'Dettaglio Carichi',
      pEnvLabel: 'Carico Involucro (P_env)',
      pPessoasLabel: 'Carico Occupazione (P_persone)',
      pTrafoLabel: 'Carico Trasformatori (P_trafo)',
      pQuadrosLabel: 'Carico Quadri (P_quadri)',
      transformerType: 'Trasformatore',
      switchboardType: 'Quadro (MT/BT)',
      numColumnsLabel: 'Numero di Colonne',
      lossesEstimateMsg: 'Stima: 2.5% della Potenza',
      parametricCalcMsg: 'Calcolo paramétrico: 0.15 kW per cella/colonna.',
    },
  }
};
